import {useEffect,useState} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import DesignViewer from './DesignViewer';
import EngineeringPanels from './EngineeringPanels';
import Phase4Panels from './Phase4Panels';
import {metricRows,statusLabel,type Alternative} from './model';
import './design.css';
import './engineering.css';

function useCadGlbUrl(api:string,token:string,projectId:string,versionId:string,runId:string|null):string|null{
  const [url,setUrl]=useState<string|null>(null);
  useEffect(()=>{
    if(!runId){setUrl(null);return;}
    let cancelled=false;
    async function load(){
      const r=await fetch(`${api}/projects/${projectId}/versions/${versionId}/cad/jobs/${runId}/artifacts`,{headers:{Authorization:`Bearer ${token}`}});
      if(!r.ok){if(!cancelled)setUrl(null);return;}
      const d=await r.json();
      const glb=d.artifacts?.find((a:any)=>a.kind==='glb');
      if(glb && !cancelled)setUrl(`${api}/projects/${projectId}/versions/${versionId}/cad/artifacts/${glb.id}/download`);
    }
    load();
    return ()=>{cancelled=true};
  },[api,token,projectId,versionId,runId]);
  return url;
}

export default function DesignWorkspace({api,token,projectId,organizationId,version}:{api:string;token:string;projectId:string;organizationId:string;version:any}){
  const client=useQueryClient();const [selected,setSelected]=useState('');const [compare,setCompare]=useState(false);const [lastRun,setLastRun]=useState<any>(null);const [workspacePanel,setWorkspacePanel]=useState('Design');const [rateScheduleId,setRateScheduleId]=useState('');
  async function request(path:string,init:RequestInit={}){const r=await fetch(api+path,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...init.headers}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error?.message||`Request failed (${r.status})`);return d}
  const base=`/projects/${projectId}/versions/${version.id}/design`;
  const alternatives=useQuery({queryKey:['design-alternatives',projectId,version.id],queryFn:()=>request(`${base}/alternatives`)});
  const list:Alternative[]=alternatives.data?.alternatives||[];
  useEffect(()=>{if(!list.some(x=>x.id===selected))setSelected(list.find(x=>x.status==='SELECTED')?.id||list[0]?.id||'')},[alternatives.data,version.id]);
  const current=list.find(x=>x.id===selected);
  const geometry=useQuery({queryKey:['geometry',projectId,version.id,selected],queryFn:()=>request(`${base}/alternatives/${selected}/geometry`),enabled:!!selected});
  const runId=geometry.data?.provenance?.cad_job_run_id??null;
  const cadGlbUrl=useCadGlbUrl(api,token,projectId,version.id,runId);
  const engineering=useQuery({queryKey:['engineering',projectId,version.id,selected,rateScheduleId],queryFn:()=>request(`${base}/alternatives/${selected}/engineering${rateScheduleId?`?rate_schedule_id=${rateScheduleId}`:''}`),enabled:!!selected&&['Quantities','Cost','Structure','Regulations','Validation'].includes(workspacePanel),retry:false});
  const schedules=useQuery({queryKey:['rate-schedules',organizationId],queryFn:()=>request(`/engineering/rate-schedules?organization_id=${organizationId}`),enabled:workspacePanel==='Cost'});
  const engineeringComparison=useQuery({queryKey:['engineering-comparison',projectId,version.id],queryFn:()=>request(`/projects/${projectId}/versions/${version.id}/engineering/comparison`),enabled:compare});
  const calculate=useMutation({mutationFn:()=>request(`${base}/alternatives/${selected}/engineering/calculate`,{method:'POST',body:JSON.stringify({rate_schedule_id:rateScheduleId||null})}),onSuccess:async()=>{await client.invalidateQueries({queryKey:['engineering',projectId,version.id,selected]});await client.invalidateQueries({queryKey:['engineering-comparison',projectId,version.id]})}});
  const generate=useMutation({mutationFn:()=>request(`${base}/generate`,{method:'POST'}),onSuccess:async data=>{setLastRun(data);await client.invalidateQueries({queryKey:['design-alternatives',projectId,version.id]});await client.invalidateQueries({queryKey:['design-comparison',projectId,version.id]})}});
  const select=useMutation({mutationFn:(id:string)=>request(`${base}/alternatives/${id}/select`,{method:'POST',body:JSON.stringify({reason:'Selected by user after explicit alternative review'})}),onSuccess:()=>client.invalidateQueries({queryKey:['design-alternatives',projectId,version.id]})});
  if(alternatives.isLoading)return <div className="design-state" role="status">Loading design alternatives for {version.label}…</div>;
  if(alternatives.error)return <div className="design-state error" role="alert"><b>Design workspace could not load.</b><span>{(alternatives.error as Error).message}</span></div>;
  return <section className="design-workspace"><header className="design-head"><div><p className="eyebrow">COMPUTATIONAL DESIGN / {version.label}</p><h2>Design alternatives</h2><p>Derived from World Model <code>{alternatives.data?.world_model_hash?.slice(0,16)}…</code></p></div><div className="design-actions"><button className="btn outline" aria-pressed={compare} onClick={()=>{setWorkspacePanel('Design');setCompare(!compare)}} disabled={list.length<2}>Compare</button><button className="btn primary" disabled={generate.isPending||version.status!=='COMMITTED'} onClick={()=>generate.mutate()}>{generate.isPending?'Generating from canonical model…':list.length?'Regenerate deterministically':'Generate alternatives'}</button></div></header>
  {version.status!=='COMMITTED'&&<div className="design-warning">Design generation unavailable: commit this World Model version first.</div>}
  {generate.error&&<div className="design-state error" role="alert"><b>Design generation could not complete.</b><span>{(generate.error as Error).message}</span></div>}
  {lastRun&&<div className="generation-progress" aria-live="polite"><b>{lastRun.alternative_ids.length} alternatives ready</b>{lastRun.progress.map((x:any)=><span key={x.stage}>✓ {x.stage.replaceAll('_',' ')}</span>)}</div>}
  {!!list.length&&<nav className="engineering-nav" aria-label="Design and engineering views">{['Design','Quantities','Cost','Structure','Regulations','Validation','AI / Workflow','Evidence','Review'].map(x=><button key={x} aria-pressed={workspacePanel===x} onClick={()=>{setWorkspacePanel(x);setCompare(false)}}>{x}</button>)}</nav>}
  {!list.length?<div className="design-empty"><div className="empty-cube">◇</div><h3>No design alternatives generated yet</h3><p>Generate deterministic alternatives from the current canonical World Model.</p></div>:<div className="design-grid"><aside className="alternative-rail" aria-label="Design alternatives">{list.map(a=><button key={a.id} className={`alternative-card ${selected===a.id?'active':''} ${a.status.toLowerCase()}`} onClick={()=>setSelected(a.id)}><span className="strategy">{a.strategy_id.replace('_',' ')}</span><b>{a.name}</b><dl><div><dt>GFA</dt><dd>{fmt(a.metrics.gross_floor_area_m2)} m²</dd></div><div><dt>Coverage</dt><dd>{pct(a.metrics.site_coverage_ratio)}</dd></div><div><dt>Height</dt><dd>{fmt(a.metrics.building_height_m)} m</dd></div><div><dt>Floors</dt><dd>{a.metrics.floor_count}</dd></div></dl><em>{statusLabel(a.status)}</em></button>)}</aside>
  <main className="design-main">{['AI / Workflow','Evidence','Review'].includes(workspacePanel)?<Phase4Panels panel={workspacePanel} api={api} token={token} projectId={projectId} version={version} rateScheduleId={rateScheduleId}/>:workspacePanel!=='Design'?<EngineeringPanels panel={workspacePanel} data={engineering.data} error={engineering.error} loading={engineering.isLoading} onCalculate={()=>calculate.mutate()} calculating={calculate.isPending} schedules={schedules.data||[]} scheduleId={rateScheduleId} setScheduleId={setRateScheduleId}/>:compare?<Comparison alternatives={list} engineering={engineeringComparison.data?.alternatives||[]} onOpen={id=>{setSelected(id);setCompare(false)}}/>:geometry.isLoading?<div className="design-state" role="status">Loading persisted Geometry IR…</div>:geometry.error?<div className="design-state error" role="alert">{(geometry.error as Error).message}</div>:geometry.data?.geometry_ir&&<DesignViewer ir={geometry.data.geometry_ir} geometryHash={geometry.data.geometry_hash} cadGlbUrl={cadGlbUrl}/>}</main>
  <aside className="design-inspector">{current&&<Inspector alternative={current} geometry={geometry.data} onSelect={()=>select.mutate(current.id)} selecting={select.isPending}/>}</aside></div>}
  </section>
}
function Inspector({alternative:a,geometry,onSelect,selecting}:{alternative:Alternative;geometry:any;onSelect:()=>void;selecting:boolean}){const [panel,setPanel]=useState('metrics');return <div><div className="inspector-tabs">{['metrics','constraints','why','provenance'].map(x=><button className={panel===x?'active':''} onClick={()=>setPanel(x)} key={x}>{x}</button>)}</div>
  {panel==='metrics'&&<div className="metric-list"><Metric label="Gross floor area" value={`${fmt(a.metrics.gross_floor_area_m2)} m²`}/><Metric label="Footprint" value={`${fmt(a.metrics.building_footprint_m2)} m²`}/><Metric label="Coverage" value={pct(a.metrics.site_coverage_ratio)}/><Metric label="Open site" value={`${fmt(a.metrics.open_site_area_m2)} m²`}/><Metric label="Floors" value={String(a.metrics.floor_count)}/><Metric label="Height" value={`${fmt(a.metrics.building_height_m)} m`}/><Metric label="Efficiency" value={pct(a.metrics.efficiency_ratio)}/></div>}
  {panel==='constraints'&&<div className="constraint-list">{a.constraint_results.map((x:any)=><div className={`constraint ${x.status.toLowerCase()}`} key={x.parameter}><b>{x.status==='PASS'?'✓':x.status==='UNKNOWN'?'?':'△'} {x.parameter.replaceAll('_',' ')}</b><span>{x.classification} · actual {x.actual??'unknown'} · required {x.required??'unknown'} {x.unit||''}</span></div>)}</div>}
  {panel==='why'&&<div className="why-panel"><h3>{a.reasoning.strategy_name}</h3><p>{a.reasoning.purpose}</p><Metric label="Primary objective" value={a.reasoning.primary_objective}/><Metric label="Key result" value={a.reasoning.key_result}/><Metric label="Target GFA" value={`${fmt(a.reasoning.target_gfa_m2)} m²`}/><Metric label="Actual GFA" value={`${fmt(a.reasoning.actual_gfa_m2)} m²`}/><h4>Trade-offs</h4>{a.tradeoffs.map((x:any)=><p key={x.metric}><b>{x.metric.replaceAll('_',' ')}</b><br/>{x.effect}</p>)}<div className="safety-note">Preliminary computational design. Human review required. Not for construction.</div></div>}
  {panel==='provenance'&&<div className="provenance-list"><Metric label="World Model hash" value={a.input_world_model_hash}/><Metric label="Design hash" value={a.design_hash}/><Metric label="Geometry hash" value={geometry?.geometry_hash||a.geometry_hash}/><Metric label="Design engine" value={`ParametricMassingEngine ${a.design_engine_version}`}/><Metric label="Config" value={a.config_version}/><Metric label="Strategy" value={`${a.strategy_id} ${a.provenance?.candidate_key||''}`}/><Metric label="Geometry engine" value={geometry?`${geometry.engine_name} ${geometry.engine_version}`:'Loading…'}/></div>}
  <button className="select-design" disabled={selecting||a.status==='STALE'||a.status==='SELECTED'} onClick={onSelect}>{a.status==='SELECTED'?'Selected direction':selecting?'Selecting…':'Select design direction'}</button></div>}
function Comparison({alternatives,engineering,onOpen}:{alternatives:Alternative[];engineering:any[];onOpen:(id:string)=>void}){const rows=metricRows(alternatives);const byId=new Map<string,any>(engineering.map((x:any)=>[x.alternative_id,x]));const engineeringRows=[{key:'quantity status',values:alternatives.map(a=>byId.get(a.id)?.quantity_status||'NOT_CALCULATED')},{key:'conceptual cost',values:alternatives.map(a=>{const x=byId.get(a.id);return x?.cost_total?`${x.cost_currency} ${fmt(x.cost_total)}`:(x?.cost_status||'COST_UNAVAILABLE')})},{key:'structural concept',values:alternatives.map(a=>byId.get(a.id)?.structural_system||'NOT_CALCULATED')},{key:'regulatory result',values:alternatives.map(a=>byId.get(a.id)?.regulatory_status||'NOT_CALCULATED')},{key:'engineering validation',values:alternatives.map(a=>byId.get(a.id)?.validation_status||'NOT_CALCULATED')}];return <div className="comparison-panel"><h3>Alternative trade-off comparison</h3><p>No single optimal design is claimed.</p><div className="comparison-table"><div className="comparison-row head"><b>Metric</b>{alternatives.map(a=><button onClick={()=>onOpen(a.id)} key={a.id}>{a.name}<small>{a.strategy_id}</small></button>)}</div>{rows.map(row=><div className="comparison-row" key={row.key}><b>{row.key.replaceAll('_',' ')}</b>{row.values.map((v,i)=><span key={i}>{row.key.includes('ratio')?pct(v):fmt(v)}</span>)}</div>)}{engineeringRows.map(row=><div className="comparison-row engineering" key={row.key}><b>{row.key}</b>{row.values.map((v,i)=><span key={i}>{String(v)}</span>)}</div>)}</div></div>}
function Metric({label,value}:{label:string;value:string}){return <div className="metric-item"><span>{label}</span><b>{value}</b></div>}
function fmt(v:any){return typeof v==='number'?v.toLocaleString(undefined,{maximumFractionDigits:2}):'—'}function pct(v:any){return typeof v==='number'?`${(v*100).toFixed(1)}%`:'—'}