const labels:Record<string,string>={EXACT_DERIVED:'Exact derived',DERIVED_APPROXIMATION:'Derived approximation',ASSUMPTION_BASED:'Assumption based',UNKNOWN:'Unknown',NOT_SUPPORTED:'Not supported'};
export default function EngineeringPanels({panel,data,error,loading,onCalculate,calculating,schedules,scheduleId,setScheduleId}:{panel:string;data:any;error:any;loading:boolean;onCalculate:()=>void;calculating:boolean;schedules:any[];scheduleId:string;setScheduleId:(x:string)=>void}){
 if(loading)return <State>Loading persisted engineering artifacts…</State>;
 if(error||!data)return <div className="engineering-empty"><h3>Engineering artifacts not calculated</h3><p>Calculate deterministic quantities, structural concept, no-rule regulatory evaluation, and validation from the persisted geometry.</p><button className="btn primary" disabled={calculating} onClick={onCalculate}>{calculating?'Calculating…':'Calculate engineering'}</button>{error&&<small>{error.message}</small>}</div>;
 if(panel==='Quantities')return <Panel title="Quantities" status={data.quantity?.status} provenance={data.quantity}><div className="quantity-table">{data.quantity.quantities.map((q:any)=><div className="quantity-row" key={q.code}><div><b>{q.label}</b><small>{q.source}</small></div><strong>{q.value==null?'—':fmt(q.value)} <i>{q.unit}</i></strong><span className={`type ${q.type.toLowerCase()}`}>{labels[q.type]||q.type}</span>{q.uncertainty&&<small className="range">Range {fmt(q.uncertainty.lower_bound)}–{fmt(q.uncertainty.upper_bound)} {q.unit}<br/>{q.uncertainty.basis}</small>}</div>)}</div></Panel>;
 if(panel==='Cost')return <Panel title="Conceptual Cost" status={data.cost?.status||'COST_UNAVAILABLE'} provenance={data.cost}>{data.cost?<><div className="cost-hero"><span>Base estimate</span><b>{money(data.cost.total_cost,data.cost.currency)}</b><small>Range {money(data.cost.low_estimate,data.cost.currency)} – {money(data.cost.high_estimate,data.cost.currency)}</small></div><p className="basis">{data.cost.basis.replaceAll('_',' ')} · {data.cost.uncertainty.classification}</p><div className="cost-lines">{data.cost.breakdown.map((x:any)=><div key={x.item_code}><span>{x.category} / {x.description}<small>{fmt(x.quantity)} {x.unit} × {money(x.rate,x.currency)}</small></span><b>{money(x.line_cost,x.currency)}</b></div>)}</div><h4>Sensitivity</h4>{data.cost.sensitivity.map((x:any)=><div className="sensitivity" key={x.variable}><b>{x.variable} {x.change}</b><span>→ {money(x.total_cost_change,data.cost.currency)}</span><small>{x.basis}</small></div>)}</>:<><div className="unavailable"><b>COST UNAVAILABLE</b><p>{data.cost_error?.message||'No sourced rate schedule selected.'}</p></div><RatePicker schedules={schedules} value={scheduleId} setValue={setScheduleId}/><button className="btn primary" disabled={!scheduleId||calculating} onClick={onCalculate}>Calculate with selected schedule</button></>}</Panel>;
 if(panel==='Structure')return <Panel title="Preliminary Structural Concept" status={data.structure.status} provenance={data.structure}><div className="structure-grid"><Field label="System" value={data.structure.structural_system}/><Field label="Grid" value={data.structure.grid.status==='CONCEPTUAL'?`${fmt(data.structure.grid.x_spacing_m)} m × ${fmt(data.structure.grid.y_spacing_m)} m`:'UNKNOWN'}/><Field label="Vertical system" value={data.structure.vertical_system}/><Field label="Lateral system" value={data.structure.lateral_system}/><Field label="Foundation" value={data.structure.foundation_concept}/></div><h4>Warnings and unknowns</h4>{data.structure.warnings.map((x:any)=><div className="engineering-warning" key={x.code}><b>⚠ {x.code.replaceAll('_',' ')}</b><span>{x.message}</span></div>)}<div className="disclaimer">{data.structure.disclaimer}</div></Panel>;
 if(panel==='Regulations')return <Panel title="Regulatory Evaluation" status={data.regulatory.overall_status} provenance={data.regulatory}><p className="basis">Jurisdiction: {data.regulatory.jurisdiction} · Ruleset: {data.regulatory.ruleset.version}</p>{data.regulatory.results.map((x:any)=><div className={`rule-result ${x.status.toLowerCase()}`} key={x.rule_code}><span className="rule-status">{x.status==='NOT_APPLICABLE'?'N/A':x.status}</span><div><b>{x.title}</b><small>{x.reason}</small><small>{x.calculation} · source {x.provenance.source_reference||'none configured'}</small></div></div>)}<div className="disclaimer">{data.regulatory.notice}</div></Panel>;
 return <Panel title="Engineering Validation" status={data.validation.status} provenance={data.validation}>{data.validation.checks.map((x:any)=><div className={`validation-check ${x.status.toLowerCase()}`} key={x.code}><span>{x.status}</span><div><b>{x.category} · {x.code.replaceAll('_',' ')}</b><small>{x.message}</small></div></div>)}<div className="validation-summary"><b>Review Required</b><span>{data.validation.summary.PASS} pass · {data.validation.summary.WARNING} warnings · {data.validation.summary.UNKNOWN} unknown</span></div></Panel>
}
function Panel({title,status,provenance,children}:{title:string;status:string;provenance:any;children:any}){return <section className="engineering-panel"><header><div><p className="eyebrow">PHASE 3 / PRELIMINARY</p><h3>{title}</h3></div><span className={`artifact-status ${String(status).toLowerCase()}`}>{status}</span></header>{children}<details className="engineering-provenance"><summary>Artifact provenance</summary><div className="prov-grid"><Field label="Engine" value={`${provenance?.engine_name||'—'} ${provenance?.engine_version||''}`}/><Field label="Configuration" value={provenance?.config_version||'—'}/><Field label="Input geometry" value={provenance?.input_geometry_hash||provenance?.input_hashes?.geometry_hash||'—'}/><Field label="Output hash" value={provenance?.quantity_hash||provenance?.cost_hash||provenance?.concept_hash||provenance?.regulatory_hash||provenance?.validation_hash||'—'}/><Field label="Generated" value={provenance?.created_at||'—'}/></div></details></section>}
function RatePicker({schedules,value,setValue}:{schedules:any[];value:string;setValue:(x:string)=>void}){return <label className="rate-picker">Rate schedule<select aria-label="Rate schedule" value={value} onChange={e=>setValue(e.target.value)}><option value="">Select a sourced schedule</option>{schedules.map(x=><option value={x.id} key={x.id}>{x.name} / {x.version} / {x.source_type}</option>)}</select></label>}
function Field({label,value}:{label:string;value:any}){return <div className="engineering-field"><span>{label}</span><b>{String(value)}</b></div>};function State({children}:{children:any}){return <div className="design-state" role="status">{children}</div>};function fmt(v:any){return typeof v==='number'?v.toLocaleString(undefined,{maximumFractionDigits:2}):'—'};function money(v:any,c='SAR'){return typeof v==='number'?`${c} ${v.toLocaleString(undefined,{maximumFractionDigits:0})}`:'—'}
