import {useState} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {REVIEW_ACTIONS} from './phase4Model';

type Props={panel:string;api:string;token:string;projectId:string;version:any;rateScheduleId:string};
export default function Phase4Panels({panel,api,token,projectId,version,rateScheduleId}:Props){
 const qc=useQueryClient();const [question,setQuestion]=useState('Summarize the current feasibility evidence and unknowns.');const [rationale,setRationale]=useState('Reviewed the preliminary feasibility evidence and limitations.');
 async function request(path:string,init:RequestInit={}){const r=await fetch(api+path,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...init.headers}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error?.message||`Request failed (${r.status})`);return d}
 const workflows=useQuery({queryKey:['p4-workflows',projectId],queryFn:()=>request(`/projects/${projectId}/workflows`),enabled:['AI / Workflow','Review'].includes(panel)});const latest=workflows.data?.workflows?.[0];
 const workflow=useQuery({queryKey:['p4-workflow',latest?.id],queryFn:()=>request(`/workflows/${latest.id}`),enabled:!!latest?.id});
 const evidence=useQuery({queryKey:['p4-evidence',projectId,version.id],queryFn:()=>request(`/projects/${projectId}/evidence?version_id=${version.id}`),enabled:panel==='Evidence'});
 const providers=useQuery({queryKey:['p4-providers'],queryFn:()=>request('/ai/providers/status'),enabled:panel==='AI / Workflow'});const usage=useQuery({queryKey:['p4-usage',projectId],queryFn:()=>request(`/projects/${projectId}/ai/usage`),enabled:panel==='AI / Workflow'});
 const impact=useQuery({queryKey:['p4-impact',projectId,version.id],queryFn:()=>request(`/projects/${projectId}/versions/${version.id}/change-impact`),enabled:panel==='AI / Workflow'});
 const start=useMutation({mutationFn:()=>request(`/projects/${projectId}/workflows/feasibility`,{method:'POST',headers:{'Idempotency-Key':`ui-${version.id}-${Date.now()}`},body:JSON.stringify({version_ref:version.id,rate_schedule_id:rateScheduleId||null})}),onSuccess:()=>qc.invalidateQueries({queryKey:['p4-workflows',projectId]})});
 const assistant=useMutation({mutationFn:()=>request(`/projects/${projectId}/assistant`,{method:'POST',body:JSON.stringify({question,version_ref:version.id})})});
 const review=useMutation({mutationFn:(decision:string)=>request('/reviews',{method:'POST',body:JSON.stringify({project_id:projectId,project_version_id:version.id,workflow_id:latest?.id,artifact_id:'feasibility-package',artifact_version:'1',artifact_version_ids:[],world_model_version:version.label,source_hash:workflow.data?.input_hash||'not-available',decision,rationale})}),onSuccess:()=>{qc.invalidateQueries({queryKey:['p4-workflow',latest?.id]});qc.invalidateQueries({queryKey:['p4-workflows',projectId]})}});
 if(panel==='Evidence')return <section className="p4-panel"><header><p className="eyebrow">TRACEABILITY</p><h3>Evidence graph</h3><p>Immutable references connecting canonical inputs, deterministic artifacts, bounded decisions, and human review.</p></header>{evidence.isLoading?<p>Loading evidence…</p>:!evidence.data?.nodes?.length?<div className="p4-empty">No evidence graph yet. Run the feasibility workflow first.</div>:<div className="evidence-grid">{evidence.data.nodes.map((n:any)=><article key={n.id}><span>{n.source_type}</span><b>{n.label}</b><code>{n.evidence_hash.slice(0,16)}…</code><small>Evidence ID {n.id}</small></article>)}</div>}</section>;
 if(panel==='Review')return <section className="p4-panel"><header><p className="eyebrow">MANDATORY HUMAN AUTHORITY</p><h3>Review gate</h3></header><div className="review-gate"><b>{workflow.data?.state||latest?.state||'NO WORKFLOW'}</b><p>Acceptance is for preliminary feasibility use only. It is not certification, regulatory approval, legal advice, tender pricing, market assurance, or construction readiness.</p><textarea aria-label="Review rationale" value={rationale} onChange={e=>setRationale(e.target.value)}/><div>{REVIEW_ACTIONS.map(x=><button key={x} disabled={workflow.data?.state!=='WAITING_HUMAN_REVIEW'||review.isPending} onClick={()=>review.mutate(x)}>{x.replaceAll('_',' ')}</button>)}</div>{review.error&&<p role="alert">{(review.error as Error).message}</p>}</div></section>;
 const wf=workflow.data;return <section className="p4-panel"><header className="p4-head"><div><p className="eyebrow">AI-ASSISTED / DETERMINISTIC AUTHORITY</p><h3>Feasibility workflow</h3><p>Bounded orchestration. No autonomous agent loop.</p></div><button className="btn primary" disabled={start.isPending||version.status!=='COMMITTED'} onClick={()=>start.mutate()}>{start.isPending?'Running bounded workflow…':'Run feasibility workflow'}</button></header><div className="provider-strip"><span>LLM <b>{providers.data?.llm?.provider||'loading'}</b></span><span>State <b>{wf?.state||latest?.state||'NOT STARTED'}</b></span><span>AI calls <b>{usage.data?.usage?.reduce((n:number,x:any)=>n+x.calls,0)||0}</b></span><span>Estimated cost <b>${(usage.data?.usage?.reduce((n:number,x:any)=>n+x.estimated_cost_usd,0)||0).toFixed(4)}</b></span></div>{wf?.steps&&<div className="workflow-timeline">{wf.steps.map((s:any)=><div key={s.id} className={s.state.toLowerCase()}><i/><section><b>{s.key.replaceAll('_',' ')}</b><span>{s.state} · attempt {s.attempts}/{s.max_attempts}</span>{s.error_message&&<em>{s.error_message}</em>}</section></div>)}</div>}<div className="impact-summary"><h4>Change impact</h4><p>{impact.data?.changed_fields?.length||0} changed fields · {impact.data?.affected?.length||0} affected · {impact.data?.unaffected?.length||0} unaffected</p><small>Old artifacts remain immutable; dependency hashes determine selective recomputation.</small></div><div className="assistant-box"><h4>Read-only project assistant</h4><textarea aria-label="Assistant question" value={question} onChange={e=>setQuestion(e.target.value)}/><button onClick={()=>assistant.mutate()} disabled={assistant.isPending}>Ask from evidence</button>{assistant.data&&<div className={`assistant-answer ${assistant.data.answer.grounding_status.toLowerCase()}`}><b>{assistant.data.answer.grounding_status}</b><p>{assistant.data.answer.summary}</p><small>{assistant.data.answer.evidence_ids.length} evidence IDs cited</small></div>}</div></section>;
}
