import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import './style.css';
import GeometryViewer from './GeometryViewer';
const queryClient = new QueryClient();
const API = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8000/api/v1';
const Icon=({name}:{name:string})=><span className="ico" aria-hidden="true">{{grid:'▦',building:'⌂',layers:'▱',file:'▤',settings:'⚙',search:'⌕',plus:'＋',arrow:'↗',chevron:'⌄',logout:'⇥',cube:'◇',shield:'⬡',activity:'⌁',menu:'☰',close:'×'}[name]||'·'}</span>;
function App(){
 const [token,setToken]=useState(sessionStorage.getItem('token')||'');const [orgs,setOrgs]=useState<any[]>([]);const [projects,setProjects]=useState<any[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [register,setRegister]=useState(false);const [activeProject,setActiveProject]=useState<any|null>(null);const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [name,setName]=useState('');const [orgName,setOrgName]=useState('');const [projectName,setProjectName]=useState('');const [query,setQuery]=useState('');const [nav,setNav]=useState('Overview');
 async function request(path:string,init:RequestInit={}){const r=await fetch(API+path,{...init,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`} :{}),...init.headers}});const data=await r.json().catch(()=>({detail:`Request failed (${r.status})`}));if(!r.ok)throw new Error(data.detail||'Request failed');return data;}
 async function load(){setBusy(true);setError('');try{const o=await request('/organizations');setOrgs(o);if(o[0])setProjects(await request('/projects?organization_id='+o[0].id));else setProjects([]);}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 useEffect(()=>{if(token)load()},[token]);
 async function auth(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const d=await request(register?'/auth/register':'/auth/login',{method:'POST',body:JSON.stringify(register?{email,name,password,organization_name:orgName}:{email,password})});sessionStorage.setItem('token',d.access_token);setToken(d.access_token)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function createProject(e:React.FormEvent){e.preventDefault();if(!orgs[0])return;setBusy(true);try{await request('/projects',{method:'POST',body:JSON.stringify({organization_id:orgs[0].id,name:projectName,building_type:'commercial',location:'Saudi Arabia'})});setProjectName('');await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 const filtered=useMemo(()=>projects.filter(p=>String(p.name).toLowerCase().includes(query.toLowerCase())),[projects,query]);
 if(!token)return <div className="auth-page"><div className="auth-aside"><div className="brand"><span className="brand-mark">N</span> NAZMAK</div><div className="auth-pitch"><div className="eyebrow">BUILDING FEASIBILITY PLATFORM</div><h1>Make the<br/>first decision<br/><em>count.</em></h1><p>A considered workspace for early-stage commercial development in Saudi Arabia.</p><div className="auth-foot">DESIGN WITH EVIDENCE&nbsp; / &nbsp;BUILD WITH CONFIDENCE</div></div></div><div className="auth-main"><form className="auth-card" onSubmit={auth}><div className="eyebrow">YOUR WORKSPACE</div><h2>{register?'Create your account':'Welcome back'}</h2><p className="muted">{register?'Set up your organization to begin.':'Sign in to continue to your projects.'}</p>{register&&<><label>Full name<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Your name"/></label><label>Organization<input required value={orgName} onChange={e=>setOrgName(e.target.value)} placeholder="Company name"/></label></>}<label>Work email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@company.com"/></label><label>Password<input required type="password" minLength={register?12:1} value={password} onChange={e=>setPassword(e.target.value)} placeholder={register?'At least 12 characters':'Enter your password'}/></label>{error&&<div className="alert">{error}</div>}<button className="btn primary full" disabled={busy}>{busy?'Please wait…':register?'Create account':'Sign in'} <Icon name="arrow"/></button><button type="button" className="text-btn" onClick={()=>{setRegister(!register);setError('')}}>{register?'Already have an account? Sign in':'New to Nazmak? Create an account'}</button><div className="secure-note"><Icon name="shield"/> Organization-scoped access · Secure session</div></form></div></div>;
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">N</span><span>NAZMAK<small>BUILDING INTELLIGENCE</small></span></div><div className="workspace-switch"><div className="org-avatar">{(orgs[0]?.name||'N').slice(0,1).toUpperCase()}</div><div className="org-copy"><b>{orgs[0]?.name||'Your organization'}</b><small>Workspace</small></div><Icon name="chevron"/></div><div className="nav-label">WORKSPACE</div><nav>{[['Overview','grid'],['Projects','building'],['Alternatives','layers'],['Deliverables','file']].map(([label,icon])=><button key={label} className={`nav-item ${nav===label?'selected':''}`} onClick={()=>setNav(label)}><Icon name={icon}/>{label}{label==='Projects'&&<span className="nav-count">{projects.length}</span>}</button>)}</nav><div className="sidebar-bottom"><button className="nav-item" onClick={()=>setNav('Settings')}><Icon name="settings"/>Settings</button><div className="user-chip"><div className="user-avatar">{email.slice(0,1).toUpperCase()||'U'}</div><div className="org-copy"><b>{email||'Signed in'}</b><small>Member</small></div><button className="icon-btn" aria-label="Sign out" onClick={()=>{sessionStorage.removeItem('token');setToken('');setProjects([])}}><Icon name="logout"/></button></div></div></aside>
 <main className="main-area"><header className="topbar"><div className="crumb">Workspace <span>/</span> <b>{nav}</b></div><div className="top-actions"><span className="status-dot">API connected</span><button className="icon-btn" title="Refresh" onClick={load}>↻</button><div className="user-avatar small-avatar">{email.slice(0,1).toUpperCase()||'U'}</div></div></header><div className="content"><div className="page-heading"><div><div className="eyebrow">PROJECT INTELLIGENCE / SAUDI ARABIA</div><h1>{nav==='Overview'?'Good work starts with clarity.':nav}</h1><p className="muted">A clear view of your development pipeline and feasibility work.</p></div><button className="btn primary" onClick={()=>document.getElementById('new-project')?.focus()}><Icon name="plus"/> New project</button></div>
 {error&&<div className="alert">{error}<button className="icon-btn" onClick={()=>setError('')}><Icon name="close"/></button></div>}
 <section className="metric-row"><article className="metric-card"><div className="metric-top">ACTIVE PROJECTS <span className="metric-icon"><Icon name="building"/></span></div><div className="metric-value">{projects.length.toString().padStart(2,'0')}</div><div className="metric-foot">Across your workspace</div></article><article className="metric-card"><div className="metric-top">FEASIBILITY PACKAGES <span className="metric-icon"><Icon name="layers"/></span></div><div className="metric-value">—</div><div className="metric-foot">No verified package summary</div></article><article className="metric-card"><div className="metric-top">REQUIRING REVIEW <span className="metric-icon"><Icon name="shield"/></span></div><div className="metric-value">—</div><div className="metric-foot">Review status not aggregated</div></article><article className="metric-card dark-metric"><div className="metric-top">PLATFORM STATUS <span className="live-dot"/></div><div className="metric-value text-value">Deterministic-first</div><div className="metric-foot">Decision support · Human review</div></article></section>
 <section className="section-head"><div><div className="eyebrow">YOUR PORTFOLIO</div><h2>Projects <span className="count-pill">{projects.length}</span></h2></div><div className="table-tools"><div className="search-box"><Icon name="search"/><input aria-label="Search projects" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search projects"/></div><button className="btn outline" onClick={load}>↻ Refresh</button></div></section>
 <section className="project-panel"><div className="project-table-head"><span>PROJECT</span><span>TYPE / LOCATION</span><span>VERSION</span><span>STATUS</span><span></span></div>{busy?<div className="empty-state"><div className="spinner"/>Loading workspace…</div>:filtered.length?filtered.map((p,i)=><article className="project-row" key={p.id}><div className="project-name"><div className={`project-thumb thumb-${i%3}`}><Icon name="building"/></div><div><b>{p.name}</b><small>Updated project · {p.id?.slice?.(0,8)||'Workspace item'}</small></div></div><div className="type-location">{p.building_type||'Commercial'}<small>{p.location||'Location not specified'}</small></div><div className="version">v{p.version??'—'}</div><div><span className="status-pill"><i/>{p.status||'In progress'}</span></div><button className="btn small outline" onClick={()=>setActiveProject(p)}>Open workspace <Icon name="arrow"/></button></article>):<div className="empty-state"><div className="empty-icon"><Icon name="cube"/></div><h3>{query?'No matching projects':'Your next project starts here.'}</h3><p>{query?'Try another search term.':'Create a project to begin shaping its feasibility.'}</p><form className="new-project-form" onSubmit={createProject}><input id="new-project" required value={projectName} onChange={e=>setProjectName(e.target.value)} placeholder="e.g. Riyadh Retail Centre"/><button className="btn primary" disabled={!orgs.length||busy}><Icon name="plus"/> Create project</button></form>{!orgs.length&&<small>Organization setup is required before creating a project.</small>}</div>}</section>
 <div className="bottom-note"><span><Icon name="shield"/> PRELIMINARY FEASIBILITY · HUMAN REVIEW REQUIRED</span><span>NAZMAK WORKSPACE <b>•</b> v0.1</span></div>
 {activeProject&&<GeometryViewer api={API} token={token} projectId={activeProject.id} onClose={()=>setActiveProject(null)}/>}
 </div></main></div>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><QueryClientProvider client={queryClient}><App/></QueryClientProvider></React.StrictMode>);
