import { useEffect, useMemo, useState } from 'react';
import '../../foundation.css';
import { buildFloorCountChange, summarizeSnapshot } from './model';
import DesignWorkspace from '../design/DesignWorkspace';

type Version = {id:string; version_number:number; label:string; status:string; revision_number:number; created_at:string};
type Snapshot = {project:any; version:Version; brief:any; requirements:any[]; assumptions:any[]; world_model:any; world_model_revision:any};

export default function FoundationWorkspace({api,token,project,onClose}:{api:string;token:string;project:any;onClose:()=>void}){
 const [versions,setVersions]=useState<Version[]>([]); const [selected,setSelected]=useState(''); const [snapshot,setSnapshot]=useState<Snapshot|null>(null);
 const [brief,setBrief]=useState('Six-floor commercial retail building in Riyadh, approximately 18,000 m² GFA on a 3,000 m² site, basement parking.');
 const [newFloors,setNewFloors]=useState(8); const [tab,setTab]=useState('Brief'); const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const [comparison,setComparison]=useState<any>(null);
 const headers={'Content-Type':'application/json',Authorization:`Bearer ${token}`};
 async function call(path:string,init:RequestInit={}){const response=await fetch(api+path,{...init,headers:{...headers,...init.headers}});const data=await response.json().catch(()=>({}));if(!response.ok)throw Error(data.error?.message||data.detail?.error?.message||data.detail||`Request failed (${response.status})`);return data}
 async function loadVersions(prefer?:string){const data=await call(`/projects/${project.id}/versions`);setVersions(data.versions);setSelected(prefer||selected||data.current_version_id||data.versions[0]?.id)}
 async function loadSnapshot(){if(!selected)return;setBusy(true);try{setSnapshot(await call(`/projects/${project.id}/versions/${selected}/snapshot`));setError('')}catch(e){setError(e instanceof Error?e.message:'Could not load version')}finally{setBusy(false)}}
 useEffect(()=>{loadVersions().catch(e=>setError(e.message))},[project.id]); useEffect(()=>{loadSnapshot()},[selected]);
 async function mutate(path:string,body:any,method='POST'){setBusy(true);setError('');try{const data=await call(path,{method,body:JSON.stringify(body)});await loadVersions(data.version?.id);await loadSnapshot();return data}catch(e){setError(e instanceof Error?e.message:'Mutation failed')}finally{setBusy(false)}}
 async function analyze(){if(!snapshot)return;await mutate(`/projects/${project.id}/versions/${selected}/brief`,{text:brief,expected_revision:snapshot.version.revision_number})}
 async function confirm(requirement:any){if(!snapshot)return;await mutate(`/projects/${project.id}/versions/${selected}/requirements/${requirement.id}/confirm`,{decision:'CONFIRMED',expected_revision:snapshot.version.revision_number})}
 async function decideAssumption(item:any,status:'accepted'|'rejected'){if(!snapshot)return;await mutate(`/projects/${project.id}/versions/${selected}/assumptions/${item.id}`,{status,expected_revision:snapshot.version.revision_number},'PATCH')}
 async function commit(){if(!snapshot)return;await mutate(`/projects/${project.id}/versions/${selected}/world-model`,{expected_revision:snapshot.version.revision_number,commit:true})}
 async function createVersion(){if(!snapshot)return;setBusy(true);try{const data=await call(`/projects/${project.id}/versions`,{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify(buildFloorCountChange(selected,snapshot.version.revision_number,newFloors))});await loadVersions(data.version.id);setSelected(data.version.id);setTab('World Model')}catch(e){setError(e instanceof Error?e.message:'Version creation failed')}finally{setBusy(false)}}
 async function compare(){if(versions.length<2)return;const data=await call(`/projects/${project.id}/versions/compare?version_a=${versions[1].id}&version_b=${versions[0].id}`);setComparison(data);setTab('Compare')}
 const counts=useMemo(()=>summarizeSnapshot(snapshot),[snapshot]);
 return <section className="foundation-shell"><header className="foundation-top"><div><p className="eyebrow">BUILDING BRAIN / CANONICAL STATE</p><h1>{project.name}</h1><p className="muted">Every value below belongs to an immutable project version and carries provenance.</p></div><div className="version-actions"><select value={selected} onChange={e=>setSelected(e.target.value)}>{versions.map(v=><option key={v.id} value={v.id}>{v.label} — {v.status} — {new Date(v.created_at).toLocaleString()}</option>)}</select><button className="btn outline" onClick={onClose}>Back to projects</button></div></header>
 <div className="canonical-banner"><b>{snapshot?.version.label||'—'}</b><span className={`state ${snapshot?.version.status.toLowerCase()}`}>{snapshot?.version.status||'Loading'}</span><span>Revision {snapshot?.version.revision_number||'—'}</span><span>World hash <code>{snapshot?.world_model_revision?.model_hash?.slice(0,16)||'—'}…</code></span></div>
 <nav className="phase-tabs">{['Brief','Requirements','Assumptions','World Model','Design','New Version','Compare'].map(name=><button className={tab===name?'active':''} onClick={()=>name==='Compare'?compare():setTab(name)} key={name}>{name}</button>)}</nav>
 {error&&<div className="alert">{error}</div>}{busy&&<div className="progress-line"/>}
 {tab==='Brief'&&<div className="phase-card"><p className="eyebrow">RAW BUILDING BRIEF</p><h2>Describe the building</h2><textarea value={brief} onChange={e=>setBrief(e.target.value)} placeholder="Describe your building project…"/><div className="card-actions"><button className="btn primary" disabled={busy||snapshot?.version.status!=='DRAFT'} onClick={analyze}>Analyze and persist brief</button>{snapshot?.brief&&<span>Brief revision {snapshot.brief.revision} · {snapshot.brief.content_hash.slice(0,12)}…</span>}</div></div>}
 {tab==='Requirements'&&<div className="phase-grid">{snapshot?.requirements.length?snapshot.requirements.map(item=><article className="fact-card" key={item.id}><p className="eyebrow">{item.category}</p><h3>{item.parameter.replaceAll('_',' ')}</h3><strong>{String(item.normalized_value)} {item.unit||''}</strong><p>{item.source_text}</p><div className="fact-meta"><span>{item.source_type}</span><span>{Math.round((item.confidence||0)*100)}% extraction confidence</span></div><div className={`requirement-state ${item.status.toLowerCase()}`}>{item.status}</div>{item.status==='EXTRACTED'&&<button className="btn outline small" onClick={()=>confirm(item)}>Confirm</button>}</article>):<Empty text="Analyze a brief to create requirements."/>}</div>}
 {tab==='Assumptions'&&<div className="phase-grid">{snapshot?.assumptions.length?snapshot.assumptions.map(item=><article className="fact-card assumption" key={item.id}><p className="eyebrow">SYSTEM ASSUMPTION</p><h3>{item.parameter.replaceAll('_',' ')}</h3><strong>{String(item.value)} {item.unit||''}</strong><p>{item.reason}</p><div className="fact-meta"><span>Source: {item.source}</span><span>Impacts: {item.impact_scope.join(', ')}</span></div><div className={`requirement-state ${item.status}`}>{item.status}</div>{item.status==='proposed'&&<div className="inline-actions"><button className="btn primary small" onClick={()=>decideAssumption(item,'accepted')}>Accept</button><button className="btn outline small" onClick={()=>decideAssumption(item,'rejected')}>Reject</button></div>}</article>):<Empty text="No assumptions have been proposed."/>}</div>}
 {tab==='World Model'&&<div className="world-layout"><article className="phase-card summary"><div className="summary-counts"><span><b>{counts.confirmed}</b> confirmed</span><span><b>{counts.assumed}</b> assumed</span><span><b>{counts.unknown}</b> unknown</span></div><WorldSection title="Site" value={snapshot?.world_model?.site}/><WorldSection title="Building" value={snapshot?.world_model?.building}/><WorldSection title="Parking" value={snapshot?.world_model?.parking}/><WorldSection title="Structural grid" value={snapshot?.world_model?.structural_grid}/><WorldSection title={`Levels (${snapshot?.world_model?.levels?.length||0})`} value={snapshot?.world_model?.levels}/><div className="card-actions"><button className="btn primary" disabled={snapshot?.version.status!=='DRAFT'} onClick={commit}>Commit {snapshot?.version.label}</button><span>Committing makes this version historically immutable.</span></div></article><aside className="phase-card"><p className="eyebrow">UNKNOWN VALUES</p>{snapshot?.world_model?.unknowns?.map((x:string)=><div className="unknown-row" key={x}>? {x}</div>)}<p className="eyebrow model-prov">PROVENANCE</p>{Object.entries(snapshot?.world_model?.provenance||{}).map(([key,value]:any)=><div className="prov-row" key={key}><b>{key}</b><span>{value.source_type} · {value.confirmed?'confirmed':'unconfirmed'}</span></div>)}</aside></div>}
 {tab==='Design'&&snapshot&&<DesignWorkspace api={api} token={token} projectId={project.id} organizationId={project.organization_id} version={snapshot.version}/>} 
 {tab==='New Version'&&<div className="phase-card change-card"><p className="eyebrow">EXPLICIT CANONICAL CHANGE</p><h2>Change floor count</h2><div className="change-values"><div><small>Current</small><b>{snapshot?.world_model?.building?.floor_count??'Unknown'}</b></div><span>→</span><label><small>New</small><input type="number" min="1" value={newFloors} onChange={e=>setNewFloors(+e.target.value)}/></label></div><p>Impact preview: geometry, quantities, cost, structure, regulatory, validation.</p><button className="btn primary" disabled={snapshot?.version.status!=='COMMITTED'} onClick={createVersion}>Create new version</button></div>}
 {tab==='Compare'&&<div className="phase-card"><p className="eyebrow">SEMANTIC VERSION COMPARISON</p><h2>{comparison?`${comparison.version_a.label} → ${comparison.version_b.label}`:'Two versions are required'}</h2>{comparison?.changes.map((item:any)=><div className="diff-row" key={item.parameter}><b>{item.parameter}</b><span>{JSON.stringify(item.old)}</span><i>→</i><span>{JSON.stringify(item.new)}</span></div>)}</div>}
 </section>
}
function Empty({text}:{text:string}){return <div className="empty-state"><h3>Nothing here yet</h3><p>{text}</p></div>}
function WorldSection({title,value}:{title:string;value:any}){return <section className="world-section"><h3>{title}</h3><pre>{JSON.stringify(value,null,2)}</pre></section>}
