"""Generate the AIrchitect CAD/BIM toolchain manifest from the live installation.

The manifest is the single source of truth for:
  * which third-party CAD/BIM components AIrchitect provisions and executes,
  * their pinned versions and (for FreeCAD) archive integrity hash,
  * their licenses, as observed on disk.

It is regenerated by CI and by release, and it is the input to the third-party
notices document and to the CI license gate. Nothing here is hand-maintained
license text -- every license string is read from the installed distribution
metadata, so the notices cannot drift from what is actually shipped.

Run with the API interpreter (no CAD packages required):
    python tools/cad/generate_toolchain_manifest.py \
        --freecad-root "H:/.cad-tools/freecad-1.1.3/FreeCAD_1.1.3-Windows-x86_64-py311" \
        --worker-venv "H:/.cad-tools/worker-venv" \
        --out "apps/api/app/domains/cad/toolchain_manifest.json"
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

# Packages AIrchitect provisions or directly depends on, in the order they are
# listed in the notices. Anything else found in the venv is reported under
# "additional_transitive" and is still inventoried, but is not a direct duty.
DIRECT_PACKAGES: tuple[str, ...] = (
    "cadquery-ocp",
    "ifcopenshell",
)

# Additional worker-venv packages we want an explicit license for. These arrive
# transitively but are large enough (or license-distinct enough) to be tracked
# individually rather than swept up in a "and its dependencies" clause.
TRACKED_TRANSITIVE: tuple[str, ...] = (
    "cadquery-ocp-proxy",
    "numpy",
    "vtk",
    "shapely",
    "lark",
    "pillow",
    "matplotlib",
    "kiwisolver",
    "fonttools",
    "python-dateutil",
    "isodate",
    "six",
    "typing-extensions",
    "packaging",
    "contourpy",
    "cycler",
)

# Licenses that require explicit sign-off before they may be added. Derived from
# the LGPL/AGPL analysis in docs/legal/PHASE-5-OPEN-SOURCE-LICENSE-AUDIT.md.
#
# These are matched on token boundaries, not as bare substrings: "lgpl" must not
# register as "gpl", which a naive ``in`` test would do.
COPYCLEFT_MARKERS: tuple[str, ...] = (
    "agpl",
    "gpl",
    "lgpl",
    "mpl",
    "mozilla public license",
    "eclipse public license",
    "sspl",
    "busl",
    "commons clause",
    "cddl",
)

# Map a trove license classifier onto a short SPDX-ish identifier. Used when a
# wheel ships no ``License`` field, which is common and is not itself a problem.
_CLASSIFIER_SPDX: dict[str, str] = {
    "apache software license": "Apache-2.0",
    "bsd license": "BSD",
    "mit license": "MIT",
    "gnu lesser general public license v3 or later (lgplv3+)": "LGPL-3.0-or-later",
    "gnu lesser general public license v2 or later (lgplv2+)": "LGPL-2.0-or-later",
    "gnu general public license v3 (gplv3)": "GPL-3.0",
    "python software foundation license": "PSF-2.0",
}


def _classifiers_spdx(classifiers: list[str]) -> str | None:
    """Derive a license identifier from trove classifiers.

    Several wheels in the CAD toolchain (notably ``ifcopenshell``) ship no
    ``License:`` field and declare their terms only via a classifier, so this
    fallback is load-bearing rather than cosmetic.
    """
    for classifier in classifiers:
        key = classifier.split("::")[-1].strip().lower()
        if key in _CLASSIFIER_SPDX:
            return _CLASSIFIER_SPDX[key]
    return None


def _find_markers(haystack: str) -> list[str]:
    """Return copyleft markers present in *haystack*, on token boundaries.

    Word boundaries matter: ``lgpl`` must not also report ``gpl``, and ``mpl``
    must not match inside e.g. a project name.
    """
    found: list[str] = []
    for marker in COPYCLEFT_MARKERS:
        pattern = r"(?<![a-z0-9])" + re.escape(marker) + r"(?![a-z0-9])"
        if re.search(pattern, haystack):
            found.append(marker)
    return found


@dataclass
class DistInfo:
    """License facts for one installed Python distribution, read from disk."""

    name: str
    version: str
    spdx: str | None = None
    classifiers: list[str] = field(default_factory=list)
    license_files: list[str] = field(default_factory=list)
    summary: str | None = None
    homepage: str | None = None

    @property
    def license_effective(self) -> str | None:
        """Best available license identifier for this distribution."""
        return self.spdx or _classifiers_spdx(self.classifiers)

    @property
    def copyleft(self) -> list[str]:
        """Return the copyleft family markers present in the recorded metadata."""
        haystack = " ".join(
            [
                self.license_effective or "",
                " ".join(self.classifiers),
                self.summary or "",
            ]
        ).lower()
        return _find_markers(haystack)


def _read_dist_info(site_packages: Path, package: str) -> DistInfo | None:
    """Extract metadata for *package* from *site_packages* without importing it.

    We parse the ``*.dist-info`` directories by hand rather than using
    ``importlib.metadata`` because this runs under the API interpreter, which
    does not have the CAD packages installed.
    """
    if not site_packages.is_dir():
        return None
    stem = package.replace("-", "_").lower()
    for candidate in sorted(site_packages.glob("*.dist-info")):
        if not candidate.name.lower().startswith(stem):
            continue
        meta = candidate / "METADATA"
        if not meta.is_file():
            continue
        return _parse_metadata(candidate.name, meta)
    return None


def _parse_metadata(dist_info_name: str, meta_path: Path) -> DistInfo:
    """Parse a wheel METADATA file into a :class:`DistInfo`."""
    raw = meta_path.read_text(encoding="utf-8", errors="replace")
    fields: dict[str, str] = {}
    classifiers: list[str] = []
    for line in raw.splitlines():
        if not line.strip():
            # Headers end at the first blank line; the body follows.
            if fields:
                break
            continue
        key, _, value = line.partition(":")
        key = key.strip().lower()
        value = value.strip()
        if key == "classifier":
            classifiers.append(value)
        elif key and key not in fields:
            fields[key] = value

    version = fields.get("version", "")
    if not version:
        # Fall back to the ".dist-info" directory suffix, e.g. "pillow-12.3.0.dist-info".
        m = re.match(r"^(?P<name>.+?)-(?P<ver>[^-]+)\.dist-info$", dist_info_name)
        if m:
            version = m.group("ver")

    license_files = sorted(
        str(p.relative_to(meta_path.parent))
        for p in meta_path.parent.rglob("*")
        if p.is_file() and _is_license_name(p.name)
    )

    return DistInfo(
        name=fields.get("name") or dist_info_name.split("-")[0],
        version=version,
        spdx=(fields.get("license") or "").strip() or None,
        classifiers=classifiers,
        license_files=license_files[:8],
        summary=(fields.get("summary") or "")[:200] or None,
        homepage=fields.get("home-page") or fields.get("project-url") or None,
    )


def _is_license_name(name: str) -> bool:
    """Return True for filenames that look like a license or notice."""
    lowered = name.lower()
    return (
        lowered.startswith(("license", "licence", "copying", "notice"))
        or lowered
        in {"license", "licence", "copying", "authors", "patents"}
    )


def _sha256(path: Path) -> str:
    """Return the hex SHA-256 digest of *path*, streamed."""
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _probe_freecad(freecad_cmd: Path, script: Path) -> dict[str, Any]:
    """Run *script* under FreeCADCmd and parse its JSON banner from stdout.

    FreeCAD's console prints banner and progress noise, so the probe emits a
    single machine-readable line prefixed with a sentinel and we search for it.
    """
    proc = subprocess.run(
        [str(freecad_cmd), str(script)],
        capture_output=True,
        text=True,
        timeout=300,
        check=False,
    )
    for line in proc.stdout.splitlines():
        if line.startswith("AI_MANIFEST:"):
            return json.loads(line[len("AI_MANIFEST:") :])
    raise RuntimeError(
        "FreeCAD probe did not emit AI_MANIFEST line.\n"
        f"stdout:\n{proc.stdout[-2000:]}\nstderr:\n{proc.stderr[-2000:]}"
    )


_FREECAD_PROBE = '''\
import json
import FreeCAD
import Part

payload = {
    "freecad_version": ".".join(FreeCAD.Version()[:3]),
    "freecad_build": FreeCAD.Version()[3],
    "freecad_git": (FreeCAD.Version()[7] if len(FreeCAD.Version()) > 7 else None),
    "occt_version": getattr(Part, "OCC_VERSION", "UNKNOWN"),
    "python": ".".join(str(p) for p in __import__("sys").version_info[:3]),
}
print("AI_MANIFEST:" + json.dumps(payload, sort_keys=True))
'''


def _freecad_packages_inventory(freecad_root: Path) -> list[dict[str, str]]:
    """Parse FreeCAD's own third-party manifest (``packages.txt``).

    FreeCAD ships a 236-line conda inventory but no per-package license text, so
    we record name/version/build only and let the notices document link to
    upstream rather than inventing license claims we cannot verify.
    """
    manifest = freecad_root / "packages.txt"
    if not manifest.is_file():
        return []
    rows: list[dict[str, str]] = []
    for line in manifest.read_text(encoding="utf-8", errors="replace").splitlines():
        parts = line.split()
        if len(parts) < 4 or parts[0].lower() in {"platform:", "license:"}:
            continue
        rows.append(
            {"name": parts[0], "version": parts[1], "build": parts[2], "channel": parts[3]}
        )
    return rows


def build_manifest(
    freecad_root: Path,
    worker_venv: Path,
    archive_path: Path | None = None,
) -> dict[str, Any]:
    """Assemble the manifest dictionary from the live toolchain."""
    freecad_cmd = freecad_root / "bin" / "freecadcmd.exe"
    if not freecad_cmd.is_file():
        freecad_cmd = freecad_root / "freecadcmd.exe"
    if not freecad_cmd.is_file():
        raise FileNotFoundError(f"freecadcmd.exe not found under {freecad_root}")

    probe_script = freecad_root / "_ai_manifest_probe.py"
    probe_script.write_text(_FREECAD_PROBE, encoding="utf-8")
    try:
        freecad = _probe_freecad(freecad_cmd, probe_script)
    finally:
        probe_script.unlink(missing_ok=True)

    site_packages = worker_venv / "Lib" / "site-packages"
    if not site_packages.is_dir():
        site_packages = worker_venv / "lib" / f"python{sys.version_info.major}."
        site_packages = worker_venv / "lib" / "site-packages"
    if not site_packages.is_dir():
        raise FileNotFoundError(f"worker site-packages not found under {worker_venv}")

    def collect(names: tuple[str, ...]) -> list[dict[str, Any]]:
        found: list[dict[str, Any]] = []
        for name in names:
            info = _read_dist_info(site_packages, name)
            if info is None:
                found.append({"package": name, "present": False})
                continue
            found.append(
                {
                    "package": info.name,
                    "present": True,
                    "version": info.version,
                    "license": info.spdx,
                    "license_effective": info.license_effective,
                    "license_classifiers": [
                        c for c in info.classifiers if c.lower().startswith("license")
                    ],
                    "license_files": info.license_files,
                    "copyleft_markers": info.copyleft,
                    "homepage": info.homepage,
                    "summary": info.summary,
                }
            )
        return found

    manifest: dict[str, Any] = {
        "schema_version": "1.0",
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "generator": "tools/cad/generate_toolchain_manifest.py",
        "freecad": {
            "version": freecad.get("freecad_version"),
            "build": freecad.get("freecad_build"),
            "git_commit": freecad.get("freecad_git"),
            "embedded_python": freecad.get("python"),
            "bundled_occt": freecad.get("occt_version"),
            "executable": str(freecad_cmd),
            "root": str(freecad_root),
            "license": "LGPL-2.0-or-later",
            "license_evidence": (
                "runtime banner: 'FreeCAD is free and open-source software "
                "licensed under the terms of LGPL2+ license.'; source LICENSE at "
                "https://github.com/FreeCAD/FreeCAD tag 1.1.3"
            ),
            "ships_root_license_file": (freecad_root / "LICENSE").is_file(),
            "third_party_package_count": len(_freecad_packages_inventory(freecad_root)),
        },
        "python_packages": {
            "direct": collect(DIRECT_PACKAGES),
            "transitive": collect(TRACKED_TRANSITIVE),
        },
        "copyleft_components": [],
    }

    if archive_path is not None and archive_path.is_file():
        manifest["freecad"]["archive_name"] = archive_path.name
        manifest["freecad"]["archive_sha256"] = _sha256(archive_path)
        manifest["freecad"]["archive_bytes"] = archive_path.stat().st_size

    # Roll every copyleft component into one reviewable list so the CI gate has
    # a single thing to assert on.
    for group in ("direct", "transitive"):
        for row in manifest["python_packages"][group]:
            if row.get("copyleft_markers"):
                manifest["copyleft_components"].append(
                    {
                        "package": row["package"],
                        "version": row.get("version"),
                        "license": row.get("license"),
                        "markers": row["copyleft_markers"],
                        "group": group,
                    }
                )
    manifest["copyleft_components"].append(
        {
            "package": "FreeCAD",
            "version": manifest["freecad"]["version"],
            "license": "LGPL-2.0-or-later",
            "markers": ["lgpl"],
            "group": "external-binary",
        }
    )
    manifest["copyleft_components"].append(
        {
            "package": "OCCT",
            "version": manifest["freecad"]["bundled_occt"],
            "license": "LGPL-2.1-or-later WITH Open CASCADE exception",
            "markers": ["lgpl"],
            "group": "native-library",
        }
    )

    return manifest


def main() -> int:
    """CLI entry point."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--freecad-root", type=Path, required=True)
    parser.add_argument("--worker-venv", type=Path, required=True)
    parser.add_argument("--archive", type=Path, default=None)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the on-disk manifest differs from --out (CI drift gate).",
    )
    args = parser.parse_args()

    manifest = build_manifest(args.freecad_root, args.worker_venv, args.archive)
    payload = json.dumps(manifest, indent=2, sort_keys=True) + "\n"

    if args.check:
        if not args.out.is_file():
            print(f"FAIL: manifest {args.out} does not exist", file=sys.stderr)
            return 1
        existing = json.loads(args.out.read_text(encoding="utf-8"))
        # The FreeCAD archive is ~400 MB and is usually absent from CI, so when
        # --archive is not supplied we carry the recorded integrity facts across
        # from the committed manifest instead of reporting a spurious mismatch.
        if args.archive is None:
            for key in ("archive_name", "archive_sha256", "archive_bytes"):
                if key in existing.get("freecad", {}):
                    manifest["freecad"][key] = existing["freecad"][key]
        # Ignore the timestamp so the check is stable across runs.
        for blob in (existing, manifest):
            blob.pop("generated_at", None)
        if existing != manifest:
            print(
                f"FAIL: {args.out} is out of date with the installed toolchain; "
                "regenerate it",
                file=sys.stderr,
            )
            return 1
        print(f"OK: {args.out} matches the installed toolchain")
        return 0

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(payload, encoding="utf-8")
    print(f"wrote {args.out}")
    print(f"  FreeCAD {manifest['freecad']['version']} "
          f"(OCCT {manifest['freecad']['bundled_occt']}, "
          f"Python {manifest['freecad']['embedded_python']})")
    print(f"  direct packages: "
          f"{', '.join(r['package'] + ' ' + str(r.get('version')) for r in manifest['python_packages']['direct'])}")
    print(f"  copyleft components requiring sign-off: "
          f"{len(manifest['copyleft_components'])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
