"""Phase 18 CAD/BIM job and artifact persistence.
Revision ID: 20260926_0006
Revises: 20260925_0005
"""
from typing import Sequence,Union
from alembic import op
import sqlalchemy as sa
revision:str='20260926_0006';down_revision:Union[str,None]='20260925_0005';branch_labels:Union[str,Sequence[str],None]=None;depends_on:Union[str,Sequence[str],None]=None
J=sa.JSON();NOW=sa.text('CURRENT_TIMESTAMP')
def s(v):return sa.text("'"+v+"'")

def upgrade():
 op.create_table('cad_job_runs',sa.Column('id',sa.String(36),primary_key=True),sa.Column('organization_id',sa.String(36),sa.ForeignKey('organizations.id',ondelete='CASCADE'),nullable=False),sa.Column('project_id',sa.String(36),sa.ForeignKey('projects.id',ondelete='CASCADE'),nullable=False),sa.Column('project_version_id',sa.String(36),sa.ForeignKey('project_versions.id',ondelete='CASCADE'),nullable=False),sa.Column('world_model_revision_id',sa.String(36),sa.ForeignKey('world_model_revisions.id')),sa.Column('input_world_model_hash',sa.String(64),nullable=False,server_default=s('')),sa.Column('design_alternative_id',sa.String(36),sa.ForeignKey('design_alternatives.id')),sa.Column('geometry_artifact_id',sa.String(36),sa.ForeignKey('geometry_artifacts.id')),sa.Column('job_id',sa.String(128),nullable=False,server_default=s('')),sa.Column('provider',sa.String(40),nullable=False),sa.Column('provider_engine_name',sa.String(80),nullable=False,server_default=s('')),sa.Column('provider_engine_version',sa.String(40),nullable=False,server_default=s('')),sa.Column('occt_version',sa.String(40),nullable=False,server_default=s('')),sa.Column('ifc_library_version',sa.String(40),nullable=False,server_default=s('')),sa.Column('freecad_version',sa.String(40)),sa.Column('request_hash',sa.String(64),nullable=False),sa.Column('element_count',sa.Integer(),nullable=False,server_default=sa.text('0')),sa.Column('capabilities_json',J,nullable=False,server_default=s('{}')),sa.Column('status',sa.String(24),nullable=False,server_default=s('RUNNING')),sa.Column('error_code',sa.String(100)),sa.Column('error_message',sa.Text()),sa.Column('measurements_json',J,nullable=False,server_default=s('{}')),sa.Column('validation_json',J,nullable=False,server_default=s('{}')),sa.Column('warnings_json',J,nullable=False,server_default=s('[]')),sa.Column('requested_by',sa.String(36),sa.ForeignKey('users.id'),nullable=False),sa.Column('started_at',sa.DateTime(timezone=True),nullable=False,server_default=NOW),sa.Column('completed_at',sa.DateTime(timezone=True)),sa.Column('duration_ms',sa.Integer()),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False,server_default=NOW))
 for c in ['organization_id','project_id','project_version_id','world_model_revision_id','input_world_model_hash','design_alternative_id','geometry_artifact_id','provider','request_hash','status','error_code']:op.create_index('ix_cad_job_runs_'+c,'cad_job_runs',[c])
 op.create_table('cad_artifacts',sa.Column('id',sa.String(36),primary_key=True),sa.Column('cad_job_run_id',sa.String(36),sa.ForeignKey('cad_job_runs.id',ondelete='CASCADE'),nullable=False),sa.Column('artifact_version_id',sa.String(36),sa.ForeignKey('artifact_versions.id',ondelete='CASCADE'),nullable=False),sa.Column('organization_id',sa.String(36),sa.ForeignKey('organizations.id',ondelete='CASCADE'),nullable=False),sa.Column('project_id',sa.String(36),sa.ForeignKey('projects.id',ondelete='CASCADE'),nullable=False),sa.Column('project_version_id',sa.String(36),sa.ForeignKey('project_versions.id',ondelete='CASCADE'),nullable=False),sa.Column('kind',sa.String(24),nullable=False),sa.Column('filename',sa.String(255),nullable=False),sa.Column('content_type',sa.String(120),nullable=False),sa.Column('byte_size',sa.BigInteger(),nullable=False),sa.Column('sha256',sa.String(64),nullable=False),sa.Column('storage_key',sa.String(512),nullable=False),sa.Column('media_role',sa.String(40),nullable=False,server_default=s('exchange')),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False,server_default=NOW),sa.UniqueConstraint('cad_job_run_id','kind',name='uq_cad_artifact_kind'))
 for c in ['cad_job_run_id','artifact_version_id','organization_id','project_id','project_version_id','kind','sha256']:op.create_index('ix_cad_artifacts_'+c,'cad_artifacts',[c])

def downgrade():
 for c in ['sha256','kind','project_version_id','project_id','organization_id','artifact_version_id','cad_job_run_id']:op.drop_index('ix_cad_artifacts_'+c,table_name='cad_artifacts')
 op.drop_table('cad_artifacts')
 for c in ['error_code','status','request_hash','provider','geometry_artifact_id','design_alternative_id','input_world_model_hash','world_model_revision_id','project_version_id','project_id','organization_id']:op.drop_index('ix_cad_job_runs_'+c,table_name='cad_job_runs')
 op.drop_table('cad_job_runs')
