"""Phase 4 AI-assisted durable traceable feasibility orchestration.
Revision ID: 20260925_0005
Revises: 20260925_0004
"""
from typing import Sequence,Union
from alembic import op
import sqlalchemy as sa
revision:str='20260925_0005';down_revision:Union[str,None]='20260925_0004';branch_labels:Union[str,Sequence[str],None]=None;depends_on:Union[str,Sequence[str],None]=None
J=sa.JSON();NOW=sa.text('CURRENT_TIMESTAMP')
def s(v):return sa.text("'"+v+"'")

def upgrade():
 with op.batch_alter_table('workflows') as b:
  for c in [sa.Column('current_step',sa.String(100)),sa.Column('input_hash',sa.String(64),nullable=False,server_default=s('')),sa.Column('workflow_definition_version',sa.String(40),nullable=False,server_default=s('legacy')),sa.Column('failure_class',sa.String(32)),sa.Column('failure_code',sa.String(100)),sa.Column('failure_message',sa.Text()),sa.Column('started_at',sa.DateTime(timezone=True)),sa.Column('completed_at',sa.DateTime(timezone=True)),sa.Column('metadata_json',J,nullable=False,server_default=s('{}'))]:b.add_column(c)
  b.create_index('ix_workflows_state',['state']);b.create_index('ix_workflows_input_hash',['input_hash']);b.create_index('ix_workflows_created_at',['created_at'])
 with op.batch_alter_table('workflow_tasks') as b:
  for c in [sa.Column('input_hash',sa.String(64),nullable=False,server_default=s('')),sa.Column('output_hash',sa.String(64)),sa.Column('failure_class',sa.String(32)),sa.Column('error_code',sa.String(100)),sa.Column('error_message',sa.Text()),sa.Column('artifact_version_id',sa.String(36)),sa.Column('provider',sa.String(80)),sa.Column('metadata_json',J,nullable=False,server_default=s('{}')),sa.Column('started_at',sa.DateTime(timezone=True)),sa.Column('completed_at',sa.DateTime(timezone=True))]:b.add_column(c)
  b.create_foreign_key('fk_workflow_task_artifact','artifact_versions',['artifact_version_id'],['id']);b.create_index('ix_workflow_tasks_input_hash',['input_hash']);b.create_index('ix_workflow_tasks_output_hash',['output_hash']);b.create_index('ix_workflow_tasks_artifact_version_id',['artifact_version_id'])
 with op.batch_alter_table('decision_records') as b:
  for c in [sa.Column('organization_id',sa.String(36)),sa.Column('project_id',sa.String(36)),sa.Column('workflow_id',sa.String(36)),sa.Column('step_id',sa.String(36)),sa.Column('decision_type',sa.String(80),nullable=False,server_default=s('LEGACY')),sa.Column('provider_model',sa.String(120),nullable=False,server_default=s('')),sa.Column('input_hash',sa.String(64),nullable=False,server_default=s('')),sa.Column('question_schema_version',sa.String(40),nullable=False,server_default=s('1.0.0')),sa.Column('decision',sa.String(100),nullable=False,server_default=s('')),sa.Column('probabilities_json',J,nullable=False,server_default=s('{}')),sa.Column('confidence',sa.Float()),sa.Column('input_tokens',sa.Integer()),sa.Column('output_tokens',sa.Integer()),sa.Column('cost_usd',sa.Float()),sa.Column('request_id',sa.String(160)),sa.Column('provider_error_json',J,nullable=False,server_default=s('{}')),sa.Column('human_override_json',J,nullable=False,server_default=s('{}')),sa.Column('final_disposition',sa.String(100),nullable=False,server_default=s(''))]:b.add_column(c)
  b.create_foreign_key('fk_decision_org','organizations',['organization_id'],['id'],ondelete='CASCADE');b.create_foreign_key('fk_decision_project','projects',['project_id'],['id'],ondelete='CASCADE');b.create_foreign_key('fk_decision_workflow','workflows',['workflow_id'],['id'],ondelete='SET NULL');b.create_foreign_key('fk_decision_step','workflow_tasks',['step_id'],['id'],ondelete='SET NULL')
 for c in ['organization_id','project_id','workflow_id','decision_type','input_hash']:op.create_index('ix_decision_records_'+c,'decision_records',[c])
 with op.batch_alter_table('feasibility_reviews') as b:
  for c in [sa.Column('workflow_id',sa.String(36)),sa.Column('artifact_versions_json',J,nullable=False,server_default=s('[]')),sa.Column('world_model_version',sa.String(80),nullable=False,server_default=s('')),sa.Column('status',sa.String(32),nullable=False,server_default=s('REVIEWED')),sa.Column('comments',sa.Text(),nullable=False,server_default=s('')),sa.Column('reviewed_at',sa.DateTime(timezone=True),nullable=False,server_default=NOW)]:b.add_column(c)
  b.create_foreign_key('fk_review_workflow','workflows',['workflow_id'],['id'],ondelete='SET NULL');b.create_index('ix_feasibility_reviews_project_version_id',['project_version_id']);b.create_index('ix_feasibility_reviews_workflow_id',['workflow_id']);b.create_index('ix_feasibility_reviews_status',['status'])
 op.create_table('llm_usage_records',sa.Column('id',sa.String(36),primary_key=True),sa.Column('organization_id',sa.String(36),sa.ForeignKey('organizations.id',ondelete='CASCADE'),nullable=False),sa.Column('project_id',sa.String(36),sa.ForeignKey('projects.id',ondelete='CASCADE'),nullable=False),sa.Column('project_version_id',sa.String(36),sa.ForeignKey('project_versions.id')),sa.Column('workflow_id',sa.String(36),sa.ForeignKey('workflows.id',ondelete='SET NULL')),sa.Column('provider',sa.String(80),nullable=False),sa.Column('model',sa.String(120),nullable=False),sa.Column('model_version',sa.String(120),nullable=False,server_default=s('')),sa.Column('operation',sa.String(80),nullable=False),sa.Column('prompt_version',sa.String(80),nullable=False),sa.Column('schema_version',sa.String(40),nullable=False),sa.Column('request_id',sa.String(160),nullable=False),sa.Column('input_hash',sa.String(64),nullable=False),sa.Column('context_hash',sa.String(64),nullable=False,server_default=s('')),sa.Column('output_hash',sa.String(64)),sa.Column('status',sa.String(24),nullable=False),sa.Column('input_tokens',sa.Integer()),sa.Column('output_tokens',sa.Integer()),sa.Column('total_tokens',sa.Integer()),sa.Column('latency_ms',sa.Integer(),nullable=False,server_default=sa.text('0')),sa.Column('estimated_cost_usd',sa.Float()),sa.Column('actual_cost_usd',sa.Float()),sa.Column('output_json',J,nullable=False,server_default=s('{}')),sa.Column('provenance_json',J,nullable=False,server_default=s('{}')),sa.Column('error_code',sa.String(100)),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False,server_default=NOW))
 for c in ['organization_id','project_id','project_version_id','workflow_id','operation','input_hash','status','created_at']:op.create_index('ix_llm_usage_records_'+c,'llm_usage_records',[c])
 op.create_table('evidence_nodes',sa.Column('id',sa.String(36),primary_key=True),sa.Column('organization_id',sa.String(36),sa.ForeignKey('organizations.id',ondelete='CASCADE'),nullable=False),sa.Column('project_id',sa.String(36),sa.ForeignKey('projects.id',ondelete='CASCADE'),nullable=False),sa.Column('project_version_id',sa.String(36),sa.ForeignKey('project_versions.id',ondelete='CASCADE'),nullable=False),sa.Column('workflow_id',sa.String(36),sa.ForeignKey('workflows.id',ondelete='SET NULL')),sa.Column('source_id',sa.String(160),nullable=False),sa.Column('source_type',sa.String(60),nullable=False),sa.Column('source_hash',sa.String(64),nullable=False),sa.Column('evidence_hash',sa.String(64),nullable=False),sa.Column('label',sa.String(240),nullable=False),sa.Column('payload_json',J,nullable=False,server_default=s('{}')),sa.Column('provenance_json',J,nullable=False,server_default=s('{}')),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False,server_default=NOW),sa.UniqueConstraint('project_version_id','evidence_hash',name='uq_evidence_hash_per_version'))
 for c in ['organization_id','project_id','project_version_id','workflow_id','source_id','source_type','evidence_hash','created_at']:op.create_index('ix_evidence_nodes_'+c,'evidence_nodes',[c])
 op.create_table('evidence_links',sa.Column('id',sa.String(36),primary_key=True),sa.Column('project_version_id',sa.String(36),sa.ForeignKey('project_versions.id',ondelete='CASCADE'),nullable=False),sa.Column('from_node_id',sa.String(36),sa.ForeignKey('evidence_nodes.id',ondelete='CASCADE'),nullable=False),sa.Column('to_node_id',sa.String(36),sa.ForeignKey('evidence_nodes.id',ondelete='CASCADE'),nullable=False),sa.Column('relation',sa.String(80),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False,server_default=NOW),sa.UniqueConstraint('from_node_id','to_node_id','relation',name='uq_evidence_link'))
 for c in ['project_version_id','from_node_id','to_node_id']:op.create_index('ix_evidence_links_'+c,'evidence_links',[c])
 op.create_table('decision_evaluations',sa.Column('id',sa.String(36),primary_key=True),sa.Column('decision_record_id',sa.String(36),sa.ForeignKey('decision_records.id',ondelete='CASCADE'),nullable=False),sa.Column('decision_type',sa.String(80),nullable=False),sa.Column('input_context_hash',sa.String(64),nullable=False),sa.Column('provider',sa.String(80),nullable=False),sa.Column('decision',sa.String(100),nullable=False),sa.Column('deterministic_outcome',sa.String(100),nullable=False),sa.Column('human_outcome',sa.String(100)),sa.Column('agreement',sa.Boolean()),sa.Column('confidence',sa.Float()),sa.Column('latency_ms',sa.Integer(),nullable=False,server_default=sa.text('0')),sa.Column('cost_usd',sa.Float()),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False,server_default=NOW))
 for c in ['decision_record_id','decision_type','input_context_hash']:op.create_index('ix_decision_evaluations_'+c,'decision_evaluations',[c])

def downgrade():
 op.drop_table('decision_evaluations');op.drop_table('evidence_links');op.drop_table('evidence_nodes');op.drop_table('llm_usage_records')
 for c in ['project_version_id','workflow_id','status']:op.drop_index('ix_feasibility_reviews_'+c,table_name='feasibility_reviews')
 with op.batch_alter_table('feasibility_reviews') as b:
  for c in ['reviewed_at','comments','status','world_model_version','artifact_versions_json','workflow_id']:b.drop_column(c)
 for c in ['input_hash','decision_type','workflow_id','project_id','organization_id']:op.drop_index('ix_decision_records_'+c,table_name='decision_records')
 with op.batch_alter_table('decision_records') as b:
  for c in ['final_disposition','human_override_json','provider_error_json','request_id','cost_usd','output_tokens','input_tokens','confidence','probabilities_json','decision','question_schema_version','input_hash','provider_model','decision_type','step_id','workflow_id','project_id','organization_id']:b.drop_column(c)
 for c in ['input_hash','output_hash','artifact_version_id']:op.drop_index('ix_workflow_tasks_'+c,table_name='workflow_tasks')
 with op.batch_alter_table('workflow_tasks') as b:
  for c in ['completed_at','started_at','metadata_json','provider','artifact_version_id','error_message','error_code','failure_class','output_hash','input_hash']:b.drop_column(c)
 for c in ['state','input_hash','created_at']:op.drop_index('ix_workflows_'+c,table_name='workflows')
 with op.batch_alter_table('workflows') as b:
  for c in ['metadata_json','completed_at','started_at','failure_message','failure_code','failure_class','workflow_definition_version','input_hash','current_step']:b.drop_column(c)
