"""initial integrated MVP schema

Revision ID: 20260925_0001
Revises: 
Create Date: 2026-09-25 15:00:26.161988
"""
from alembic import op
import sqlalchemy as sa

revision = '20260925_0001'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=60), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_organization_id'), 'audit_events', ['organization_id'], unique=False)
    op.create_table('regulatory_rulesets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('jurisdiction', sa.String(length=120), nullable=False),
    sa.Column('source', sa.String(length=500), nullable=False),
    sa.Column('source_reference', sa.String(length=500), nullable=False),
    sa.Column('source_version', sa.String(length=80), nullable=False),
    sa.Column('effective_date', sa.String(length=40), nullable=True),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('authoritative', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regulatory_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ruleset_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('applicability_json', sa.JSON(), nullable=False),
    sa.Column('expression_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['ruleset_id'], ['regulatory_rulesets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulatory_rules_ruleset_id'), 'regulatory_rules', ['ruleset_id'], unique=False)
    op.create_table('organization_memberships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_org_user')
    )
    op.create_index(op.f('ix_organization_memberships_organization_id'), 'organization_memberships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_memberships_user_id'), 'organization_memberships', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('building_type', sa.String(length=40), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_organization_id'), 'projects', ['organization_id'], unique=False)
    op.create_table('rate_schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('geography', sa.String(length=120), nullable=False),
    sa.Column('source', sa.String(length=500), nullable=False),
    sa.Column('source_date', sa.String(length=40), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('rates_json', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_schedules_organization_id'), 'rate_schedules', ['organization_id'], unique=False)
    op.create_table('project_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=False),
    sa.Column('parent_version_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_version_id'], ['project_versions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'version', name='uq_project_version')
    )
    op.create_index(op.f('ix_project_versions_organization_id'), 'project_versions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_project_versions_project_id'), 'project_versions', ['project_id'], unique=False)
    op.create_table('assumptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('project_version_id', sa.String(length=36), nullable=True),
    sa.Column('project_version', sa.Integer(), nullable=False),
    sa.Column('parameter', sa.String(length=120), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('impact_scope_json', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('supersedes_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_version_id'], ['project_versions.id'], ),
    sa.ForeignKeyConstraint(['supersedes_id'], ['assumptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assumptions_organization_id'), 'assumptions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_assumptions_project_id'), 'assumptions', ['project_id'], unique=False)
    op.create_index(op.f('ix_assumptions_project_version_id'), 'assumptions', ['project_version_id'], unique=False)
    op.create_table('decision_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_version_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('provider_version', sa.String(length=80), nullable=False),
    sa.Column('inputs_json', sa.JSON(), nullable=False),
    sa.Column('outputs_json', sa.JSON(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('fallback_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_version_id'], ['project_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_records_project_version_id'), 'decision_records', ['project_version_id'], unique=False)
    op.create_table('feasibility_deliverables',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('project_version_id', sa.String(length=36), nullable=True),
    sa.Column('artifact_id', sa.String(length=128), nullable=False),
    sa.Column('artifact_version', sa.String(length=128), nullable=False),
    sa.Column('source_hash', sa.String(length=256), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_version_id'], ['project_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feasibility_deliverables_organization_id'), 'feasibility_deliverables', ['organization_id'], unique=False)
    op.create_index(op.f('ix_feasibility_deliverables_project_id'), 'feasibility_deliverables', ['project_id'], unique=False)
    op.create_index(op.f('ix_feasibility_deliverables_project_version_id'), 'feasibility_deliverables', ['project_version_id'], unique=False)
    op.create_table('feasibility_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('project_version_id', sa.String(length=36), nullable=True),
    sa.Column('artifact_id', sa.String(length=128), nullable=False),
    sa.Column('artifact_version', sa.String(length=128), nullable=False),
    sa.Column('source_hash', sa.String(length=256), nullable=False),
    sa.Column('reviewer_user_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_role', sa.String(length=24), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_version_id'], ['project_versions.id'], ),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feasibility_reviews_artifact_id'), 'feasibility_reviews', ['artifact_id'], unique=False)
    op.create_index(op.f('ix_feasibility_reviews_organization_id'), 'feasibility_reviews', ['organization_id'], unique=False)
    op.create_index(op.f('ix_feasibility_reviews_project_id'), 'feasibility_reviews', ['project_id'], unique=False)
    op.create_table('requirements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('project_version_id', sa.String(length=36), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('parameter', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('extracted_value_json', sa.JSON(), nullable=True),
    sa.Column('normalized_value_json', sa.JSON(), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('provenance_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('contradiction_group', sa.String(length=80), nullable=True),
    sa.Column('supersedes_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_version_id'], ['project_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supersedes_id'], ['requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirements_organization_id'), 'requirements', ['organization_id'], unique=False)
    op.create_index(op.f('ix_requirements_project_id'), 'requirements', ['project_id'], unique=False)
    op.create_index(op.f('ix_requirements_project_version_id'), 'requirements', ['project_version_id'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('project_version_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('workflow_type', sa.String(length=100), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_version_id'], ['project_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'idempotency_key', name='uq_workflow_idempotency')
    )
    op.create_index(op.f('ix_workflows_organization_id'), 'workflows', ['organization_id'], unique=False)
    op.create_index(op.f('ix_workflows_project_id'), 'workflows', ['project_id'], unique=False)
    op.create_index(op.f('ix_workflows_project_version_id'), 'workflows', ['project_version_id'], unique=False)
    op.create_table('world_model_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('project_version_id', sa.String(length=36), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('model_json', sa.JSON(), nullable=False),
    sa.Column('model_hash', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_version_id'], ['project_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'revision', name='uq_world_revision')
    )
    op.create_index(op.f('ix_world_model_revisions_organization_id'), 'world_model_revisions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_world_model_revisions_project_id'), 'world_model_revisions', ['project_id'], unique=False)
    op.create_index(op.f('ix_world_model_revisions_project_version_id'), 'world_model_revisions', ['project_version_id'], unique=False)
    op.create_table('artifact_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('project_version_id', sa.String(length=36), nullable=False),
    sa.Column('world_model_revision_id', sa.String(length=36), nullable=True),
    sa.Column('alternative_id', sa.String(length=36), nullable=True),
    sa.Column('artifact_type', sa.String(length=60), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('provenance_json', sa.JSON(), nullable=False),
    sa.Column('input_references_json', sa.JSON(), nullable=False),
    sa.Column('output_hash', sa.String(length=64), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_version_id'], ['project_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['world_model_revision_id'], ['world_model_revisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_version_id', 'artifact_type', 'version', name='uq_artifact_version')
    )
    op.create_index(op.f('ix_artifact_versions_alternative_id'), 'artifact_versions', ['alternative_id'], unique=False)
    op.create_index(op.f('ix_artifact_versions_artifact_type'), 'artifact_versions', ['artifact_type'], unique=False)
    op.create_index(op.f('ix_artifact_versions_organization_id'), 'artifact_versions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_artifact_versions_project_id'), 'artifact_versions', ['project_id'], unique=False)
    op.create_index(op.f('ix_artifact_versions_project_version_id'), 'artifact_versions', ['project_version_id'], unique=False)
    op.create_index(op.f('ix_artifact_versions_status'), 'artifact_versions', ['status'], unique=False)
    op.create_table('workflow_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=100), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('depends_on_json', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=160), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'key', name='uq_workflow_task_key')
    )
    op.create_index(op.f('ix_workflow_tasks_workflow_id'), 'workflow_tasks', ['workflow_id'], unique=False)
    op.create_table('artifact_dependencies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artifact_version_id', sa.String(length=36), nullable=False),
    sa.Column('depends_on_artifact_version_id', sa.String(length=36), nullable=False),
    sa.Column('dependency_kind', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_version_id'], ['artifact_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['depends_on_artifact_version_id'], ['artifact_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_version_id', 'depends_on_artifact_version_id', name='uq_artifact_dependency')
    )
    op.create_index(op.f('ix_artifact_dependencies_artifact_version_id'), 'artifact_dependencies', ['artifact_version_id'], unique=False)
    op.create_index(op.f('ix_artifact_dependencies_depends_on_artifact_version_id'), 'artifact_dependencies', ['depends_on_artifact_version_id'], unique=False)
    op.create_table('deliverable_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deliverable_id', sa.String(length=36), nullable=False),
    sa.Column('artifact_version_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['artifact_version_id'], ['artifact_versions.id'], ),
    sa.ForeignKeyConstraint(['deliverable_id'], ['feasibility_deliverables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliverable_artifacts_artifact_version_id'), 'deliverable_artifacts', ['artifact_version_id'], unique=False)
    op.create_index(op.f('ix_deliverable_artifacts_deliverable_id'), 'deliverable_artifacts', ['deliverable_id'], unique=False)
    op.create_table('design_alternatives',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('design_parameters_json', sa.JSON(), nullable=False),
    sa.Column('key_metrics_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artifact_version_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('project_version_id', sa.String(length=36), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_version_id'], ['artifact_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_version_id'], ['project_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_design_alternatives_artifact_version_id'), 'design_alternatives', ['artifact_version_id'], unique=True)
    op.create_index(op.f('ix_design_alternatives_project_id'), 'design_alternatives', ['project_id'], unique=False)
    op.create_index(op.f('ix_design_alternatives_project_version_id'), 'design_alternatives', ['project_version_id'], unique=False)
    op.create_table('evidence_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artifact_version_id', sa.String(length=36), nullable=False),
    sa.Column('project_version_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=60), nullable=False),
    sa.Column('source_uri', sa.String(length=1000), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('source_version', sa.String(length=80), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('verification_method', sa.String(length=100), nullable=False),
    sa.Column('verified_by', sa.String(length=36), nullable=True),
    sa.Column('verification_status', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['artifact_version_id'], ['artifact_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_version_id'], ['project_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_records_artifact_version_id'), 'evidence_records', ['artifact_version_id'], unique=False)
    op.create_index(op.f('ix_evidence_records_project_version_id'), 'evidence_records', ['project_version_id'], unique=False)
    op.create_table('validation_runs',
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artifact_version_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('project_version_id', sa.String(length=36), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_version_id'], ['artifact_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_version_id'], ['project_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_runs_artifact_version_id'), 'validation_runs', ['artifact_version_id'], unique=True)
    op.create_index(op.f('ix_validation_runs_project_id'), 'validation_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_validation_runs_project_version_id'), 'validation_runs', ['project_version_id'], unique=False)
    op.create_table('workflow_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('from_state', sa.String(length=24), nullable=True),
    sa.Column('to_state', sa.String(length=24), nullable=False),
    sa.Column('data_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['workflow_tasks.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_events_workflow_id'), 'workflow_events', ['workflow_id'], unique=False)
    op.create_table('geometry_artifacts',
    sa.Column('alternative_id', sa.String(length=36), nullable=False),
    sa.Column('geometry_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artifact_version_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('project_version_id', sa.String(length=36), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alternative_id'], ['design_alternatives.id'], ),
    sa.ForeignKeyConstraint(['artifact_version_id'], ['artifact_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_version_id'], ['project_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geometry_artifacts_alternative_id'), 'geometry_artifacts', ['alternative_id'], unique=False)
    op.create_index(op.f('ix_geometry_artifacts_artifact_version_id'), 'geometry_artifacts', ['artifact_version_id'], unique=True)
    op.create_index(op.f('ix_geometry_artifacts_geometry_hash'), 'geometry_artifacts', ['geometry_hash'], unique=False)
    op.create_index(op.f('ix_geometry_artifacts_project_id'), 'geometry_artifacts', ['project_id'], unique=False)
    op.create_index(op.f('ix_geometry_artifacts_project_version_id'), 'geometry_artifacts', ['project_version_id'], unique=False)
    op.create_table('validation_checks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('validation_run_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('evidence_ids_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['validation_run_id'], ['validation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_checks_validation_run_id'), 'validation_checks', ['validation_run_id'], unique=False)
    op.create_table('quantity_artifacts',
    sa.Column('geometry_artifact_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artifact_version_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('project_version_id', sa.String(length=36), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_version_id'], ['artifact_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['geometry_artifact_id'], ['geometry_artifacts.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_version_id'], ['project_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quantity_artifacts_artifact_version_id'), 'quantity_artifacts', ['artifact_version_id'], unique=True)
    op.create_index(op.f('ix_quantity_artifacts_geometry_artifact_id'), 'quantity_artifacts', ['geometry_artifact_id'], unique=False)
    op.create_index(op.f('ix_quantity_artifacts_project_id'), 'quantity_artifacts', ['project_id'], unique=False)
    op.create_index(op.f('ix_quantity_artifacts_project_version_id'), 'quantity_artifacts', ['project_version_id'], unique=False)
    op.create_table('regulatory_evaluations',
    sa.Column('geometry_artifact_id', sa.String(length=36), nullable=False),
    sa.Column('ruleset_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artifact_version_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('project_version_id', sa.String(length=36), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_version_id'], ['artifact_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['geometry_artifact_id'], ['geometry_artifacts.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_version_id'], ['project_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ruleset_id'], ['regulatory_rulesets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulatory_evaluations_artifact_version_id'), 'regulatory_evaluations', ['artifact_version_id'], unique=True)
    op.create_index(op.f('ix_regulatory_evaluations_geometry_artifact_id'), 'regulatory_evaluations', ['geometry_artifact_id'], unique=False)
    op.create_index(op.f('ix_regulatory_evaluations_project_id'), 'regulatory_evaluations', ['project_id'], unique=False)
    op.create_index(op.f('ix_regulatory_evaluations_project_version_id'), 'regulatory_evaluations', ['project_version_id'], unique=False)
    op.create_table('structural_artifacts',
    sa.Column('geometry_artifact_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artifact_version_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('project_version_id', sa.String(length=36), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_version_id'], ['artifact_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['geometry_artifact_id'], ['geometry_artifacts.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_version_id'], ['project_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_structural_artifacts_artifact_version_id'), 'structural_artifacts', ['artifact_version_id'], unique=True)
    op.create_index(op.f('ix_structural_artifacts_geometry_artifact_id'), 'structural_artifacts', ['geometry_artifact_id'], unique=False)
    op.create_index(op.f('ix_structural_artifacts_project_id'), 'structural_artifacts', ['project_id'], unique=False)
    op.create_index(op.f('ix_structural_artifacts_project_version_id'), 'structural_artifacts', ['project_version_id'], unique=False)
    op.create_table('cost_estimates',
    sa.Column('quantity_artifact_id', sa.String(length=36), nullable=False),
    sa.Column('rate_schedule_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artifact_version_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('project_version_id', sa.String(length=36), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_version_id'], ['artifact_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_version_id'], ['project_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quantity_artifact_id'], ['quantity_artifacts.id'], ),
    sa.ForeignKeyConstraint(['rate_schedule_id'], ['rate_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_estimates_artifact_version_id'), 'cost_estimates', ['artifact_version_id'], unique=True)
    op.create_index(op.f('ix_cost_estimates_project_id'), 'cost_estimates', ['project_id'], unique=False)
    op.create_index(op.f('ix_cost_estimates_project_version_id'), 'cost_estimates', ['project_version_id'], unique=False)
    op.create_index(op.f('ix_cost_estimates_quantity_artifact_id'), 'cost_estimates', ['quantity_artifact_id'], unique=False)
    op.create_index(op.f('ix_cost_estimates_rate_schedule_id'), 'cost_estimates', ['rate_schedule_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cost_estimates_rate_schedule_id'), table_name='cost_estimates')
    op.drop_index(op.f('ix_cost_estimates_quantity_artifact_id'), table_name='cost_estimates')
    op.drop_index(op.f('ix_cost_estimates_project_version_id'), table_name='cost_estimates')
    op.drop_index(op.f('ix_cost_estimates_project_id'), table_name='cost_estimates')
    op.drop_index(op.f('ix_cost_estimates_artifact_version_id'), table_name='cost_estimates')
    op.drop_table('cost_estimates')
    op.drop_index(op.f('ix_structural_artifacts_project_version_id'), table_name='structural_artifacts')
    op.drop_index(op.f('ix_structural_artifacts_project_id'), table_name='structural_artifacts')
    op.drop_index(op.f('ix_structural_artifacts_geometry_artifact_id'), table_name='structural_artifacts')
    op.drop_index(op.f('ix_structural_artifacts_artifact_version_id'), table_name='structural_artifacts')
    op.drop_table('structural_artifacts')
    op.drop_index(op.f('ix_regulatory_evaluations_project_version_id'), table_name='regulatory_evaluations')
    op.drop_index(op.f('ix_regulatory_evaluations_project_id'), table_name='regulatory_evaluations')
    op.drop_index(op.f('ix_regulatory_evaluations_geometry_artifact_id'), table_name='regulatory_evaluations')
    op.drop_index(op.f('ix_regulatory_evaluations_artifact_version_id'), table_name='regulatory_evaluations')
    op.drop_table('regulatory_evaluations')
    op.drop_index(op.f('ix_quantity_artifacts_project_version_id'), table_name='quantity_artifacts')
    op.drop_index(op.f('ix_quantity_artifacts_project_id'), table_name='quantity_artifacts')
    op.drop_index(op.f('ix_quantity_artifacts_geometry_artifact_id'), table_name='quantity_artifacts')
    op.drop_index(op.f('ix_quantity_artifacts_artifact_version_id'), table_name='quantity_artifacts')
    op.drop_table('quantity_artifacts')
    op.drop_index(op.f('ix_validation_checks_validation_run_id'), table_name='validation_checks')
    op.drop_table('validation_checks')
    op.drop_index(op.f('ix_geometry_artifacts_project_version_id'), table_name='geometry_artifacts')
    op.drop_index(op.f('ix_geometry_artifacts_project_id'), table_name='geometry_artifacts')
    op.drop_index(op.f('ix_geometry_artifacts_geometry_hash'), table_name='geometry_artifacts')
    op.drop_index(op.f('ix_geometry_artifacts_artifact_version_id'), table_name='geometry_artifacts')
    op.drop_index(op.f('ix_geometry_artifacts_alternative_id'), table_name='geometry_artifacts')
    op.drop_table('geometry_artifacts')
    op.drop_index(op.f('ix_workflow_events_workflow_id'), table_name='workflow_events')
    op.drop_table('workflow_events')
    op.drop_index(op.f('ix_validation_runs_project_version_id'), table_name='validation_runs')
    op.drop_index(op.f('ix_validation_runs_project_id'), table_name='validation_runs')
    op.drop_index(op.f('ix_validation_runs_artifact_version_id'), table_name='validation_runs')
    op.drop_table('validation_runs')
    op.drop_index(op.f('ix_evidence_records_project_version_id'), table_name='evidence_records')
    op.drop_index(op.f('ix_evidence_records_artifact_version_id'), table_name='evidence_records')
    op.drop_table('evidence_records')
    op.drop_index(op.f('ix_design_alternatives_project_version_id'), table_name='design_alternatives')
    op.drop_index(op.f('ix_design_alternatives_project_id'), table_name='design_alternatives')
    op.drop_index(op.f('ix_design_alternatives_artifact_version_id'), table_name='design_alternatives')
    op.drop_table('design_alternatives')
    op.drop_index(op.f('ix_deliverable_artifacts_deliverable_id'), table_name='deliverable_artifacts')
    op.drop_index(op.f('ix_deliverable_artifacts_artifact_version_id'), table_name='deliverable_artifacts')
    op.drop_table('deliverable_artifacts')
    op.drop_index(op.f('ix_artifact_dependencies_depends_on_artifact_version_id'), table_name='artifact_dependencies')
    op.drop_index(op.f('ix_artifact_dependencies_artifact_version_id'), table_name='artifact_dependencies')
    op.drop_table('artifact_dependencies')
    op.drop_index(op.f('ix_workflow_tasks_workflow_id'), table_name='workflow_tasks')
    op.drop_table('workflow_tasks')
    op.drop_index(op.f('ix_artifact_versions_status'), table_name='artifact_versions')
    op.drop_index(op.f('ix_artifact_versions_project_version_id'), table_name='artifact_versions')
    op.drop_index(op.f('ix_artifact_versions_project_id'), table_name='artifact_versions')
    op.drop_index(op.f('ix_artifact_versions_organization_id'), table_name='artifact_versions')
    op.drop_index(op.f('ix_artifact_versions_artifact_type'), table_name='artifact_versions')
    op.drop_index(op.f('ix_artifact_versions_alternative_id'), table_name='artifact_versions')
    op.drop_table('artifact_versions')
    op.drop_index(op.f('ix_world_model_revisions_project_version_id'), table_name='world_model_revisions')
    op.drop_index(op.f('ix_world_model_revisions_project_id'), table_name='world_model_revisions')
    op.drop_index(op.f('ix_world_model_revisions_organization_id'), table_name='world_model_revisions')
    op.drop_table('world_model_revisions')
    op.drop_index(op.f('ix_workflows_project_version_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_project_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_organization_id'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_requirements_project_version_id'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_project_id'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_organization_id'), table_name='requirements')
    op.drop_table('requirements')
    op.drop_index(op.f('ix_feasibility_reviews_project_id'), table_name='feasibility_reviews')
    op.drop_index(op.f('ix_feasibility_reviews_organization_id'), table_name='feasibility_reviews')
    op.drop_index(op.f('ix_feasibility_reviews_artifact_id'), table_name='feasibility_reviews')
    op.drop_table('feasibility_reviews')
    op.drop_index(op.f('ix_feasibility_deliverables_project_version_id'), table_name='feasibility_deliverables')
    op.drop_index(op.f('ix_feasibility_deliverables_project_id'), table_name='feasibility_deliverables')
    op.drop_index(op.f('ix_feasibility_deliverables_organization_id'), table_name='feasibility_deliverables')
    op.drop_table('feasibility_deliverables')
    op.drop_index(op.f('ix_decision_records_project_version_id'), table_name='decision_records')
    op.drop_table('decision_records')
    op.drop_index(op.f('ix_assumptions_project_version_id'), table_name='assumptions')
    op.drop_index(op.f('ix_assumptions_project_id'), table_name='assumptions')
    op.drop_index(op.f('ix_assumptions_organization_id'), table_name='assumptions')
    op.drop_table('assumptions')
    op.drop_index(op.f('ix_project_versions_project_id'), table_name='project_versions')
    op.drop_index(op.f('ix_project_versions_organization_id'), table_name='project_versions')
    op.drop_table('project_versions')
    op.drop_index(op.f('ix_rate_schedules_organization_id'), table_name='rate_schedules')
    op.drop_table('rate_schedules')
    op.drop_index(op.f('ix_projects_organization_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_organization_memberships_user_id'), table_name='organization_memberships')
    op.drop_index(op.f('ix_organization_memberships_organization_id'), table_name='organization_memberships')
    op.drop_table('organization_memberships')
    op.drop_index(op.f('ix_regulatory_rules_ruleset_id'), table_name='regulatory_rules')
    op.drop_table('regulatory_rules')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('regulatory_rulesets')
    op.drop_index(op.f('ix_audit_events_organization_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
