"""Phase 3 engineering intelligence.

Revision ID: 20260925_0004
Revises: 20260925_0003
"""
from typing import Sequence,Union
from alembic import op
import sqlalchemy as sa
revision:str="20260925_0004";down_revision:Union[str,None]="20260925_0003";branch_labels:Union[str,Sequence[str],None]=None;depends_on:Union[str,Sequence[str],None]=None
J=sa.JSON();NOW=sa.text("CURRENT_TIMESTAMP")
def s(v):return sa.text("'"+v+"'")

def upgrade():
 op.create_table("rate_entries",sa.Column("id",sa.String(36),primary_key=True),sa.Column("rate_schedule_id",sa.String(36),sa.ForeignKey("rate_schedules.id",ondelete="CASCADE"),nullable=False),sa.Column("item_code",sa.String(80),nullable=False),sa.Column("category",sa.String(80),nullable=False),sa.Column("description",sa.String(240),nullable=False),sa.Column("unit",sa.String(40),nullable=False),sa.Column("rate",sa.Float(),nullable=False),sa.Column("low_rate",sa.Float()),sa.Column("high_rate",sa.Float()),sa.Column("currency",sa.String(3),nullable=False,server_default=s("SAR")),sa.Column("source_type",sa.String(32),nullable=False),sa.Column("source_reference",sa.String(500),nullable=False),sa.Column("effective_date",sa.String(40),nullable=False),sa.Column("confidence",sa.String(32),nullable=False,server_default=s("USER_DECLARED")),sa.Column("metadata_json",J,nullable=False,server_default=s("{}")),sa.UniqueConstraint("rate_schedule_id","item_code",name="uq_rate_entry_code"))
 op.create_index("ix_rate_entries_rate_schedule_id","rate_entries",["rate_schedule_id"]);op.create_index("ix_rate_entries_item_code","rate_entries",["item_code"])
 op.create_table("regulatory_results",sa.Column("id",sa.String(36),primary_key=True),sa.Column("evaluation_id",sa.String(36),sa.ForeignKey("regulatory_evaluations.id",ondelete="CASCADE"),nullable=False),sa.Column("rule_id",sa.String(36),sa.ForeignKey("regulatory_rules.id")),sa.Column("rule_code",sa.String(80),nullable=False),sa.Column("title",sa.String(200),nullable=False),sa.Column("applicability",sa.String(24),nullable=False),sa.Column("status",sa.String(24),nullable=False),sa.Column("observed_json",J),sa.Column("threshold_json",J),sa.Column("unit",sa.String(40)),sa.Column("calculation",sa.Text(),nullable=False),sa.Column("reason",sa.Text(),nullable=False),sa.Column("provenance_json",J,nullable=False,server_default=s("{}")),sa.UniqueConstraint("evaluation_id","rule_code",name="uq_regulatory_result_rule"))
 for name,col in [("ix_regulatory_results_evaluation_id","evaluation_id"),("ix_regulatory_results_rule_code","rule_code"),("ix_regulatory_results_status","status")]:op.create_index(name,"regulatory_results",[col])
 with op.batch_alter_table("quantity_artifacts") as b:
  b.add_column(sa.Column("world_model_revision_id",sa.String(36)));b.add_column(sa.Column("design_alternative_id",sa.String(36)));b.add_column(sa.Column("input_world_model_hash",sa.String(64),nullable=False,server_default=s("")));b.add_column(sa.Column("input_design_hash",sa.String(64),nullable=False,server_default=s("")));b.add_column(sa.Column("input_geometry_hash",sa.String(64),nullable=False,server_default=s("")));b.add_column(sa.Column("engine_name",sa.String(80),nullable=False,server_default=s("legacy")));b.add_column(sa.Column("engine_version",sa.String(40),nullable=False,server_default=s("legacy")));b.add_column(sa.Column("config_version",sa.String(40),nullable=False,server_default=s("legacy")));b.add_column(sa.Column("quantity_hash",sa.String(64)));b.add_column(sa.Column("status",sa.String(24),nullable=False,server_default=s("ARCHIVED")));b.add_column(sa.Column("assumptions_json",J,nullable=False,server_default=s("[]")));b.add_column(sa.Column("unknowns_json",J,nullable=False,server_default=s("[]")));b.add_column(sa.Column("uncertainty_json",J,nullable=False,server_default=s("{}")));b.add_column(sa.Column("provenance_json",J,nullable=False,server_default=s("{}")));b.add_column(sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False,server_default=NOW));b.create_foreign_key("fk_quantity_world","world_model_revisions",["world_model_revision_id"],["id"]);b.create_foreign_key("fk_quantity_alt","design_alternatives",["design_alternative_id"],["id"]);b.create_unique_constraint("uq_quantity_hash_per_version",["project_version_id","quantity_hash"])
 for n,c in [("world_model_revision_id","world_model_revision_id"),("design_alternative_id","design_alternative_id"),("quantity_hash","quantity_hash"),("status","status")]:op.create_index("ix_quantity_artifacts_"+n,"quantity_artifacts",[c])
 with op.batch_alter_table("cost_estimates") as b:
  b.add_column(sa.Column("world_model_revision_id",sa.String(36)));b.add_column(sa.Column("design_alternative_id",sa.String(36)));b.add_column(sa.Column("geometry_artifact_id",sa.String(36)));b.add_column(sa.Column("input_quantity_hash",sa.String(64),nullable=False,server_default=s("")));b.add_column(sa.Column("input_rate_schedule_hash",sa.String(64),nullable=False,server_default=s("")));b.add_column(sa.Column("engine_name",sa.String(80),nullable=False,server_default=s("legacy")));b.add_column(sa.Column("engine_version",sa.String(40),nullable=False,server_default=s("legacy")));b.add_column(sa.Column("config_version",sa.String(40),nullable=False,server_default=s("legacy")));b.add_column(sa.Column("cost_hash",sa.String(64)));b.add_column(sa.Column("currency",sa.String(3),nullable=False,server_default=s("SAR")));b.add_column(sa.Column("direct_cost",sa.Float()));b.add_column(sa.Column("total_cost",sa.Float()));b.add_column(sa.Column("low_estimate",sa.Float()));b.add_column(sa.Column("high_estimate",sa.Float()));b.add_column(sa.Column("status",sa.String(24),nullable=False,server_default=s("ARCHIVED")));b.add_column(sa.Column("assumptions_json",J,nullable=False,server_default=s("[]")));b.add_column(sa.Column("unknowns_json",J,nullable=False,server_default=s("[]")));b.add_column(sa.Column("uncertainty_json",J,nullable=False,server_default=s("{}")));b.add_column(sa.Column("provenance_json",J,nullable=False,server_default=s("{}")));b.add_column(sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False,server_default=NOW));b.create_foreign_key("fk_cost_world","world_model_revisions",["world_model_revision_id"],["id"]);b.create_foreign_key("fk_cost_alt","design_alternatives",["design_alternative_id"],["id"]);b.create_foreign_key("fk_cost_geom","geometry_artifacts",["geometry_artifact_id"],["id"]);b.create_unique_constraint("uq_cost_hash_per_version",["project_version_id","cost_hash"])
 for c in ["world_model_revision_id","design_alternative_id","geometry_artifact_id","cost_hash","status"]:op.create_index("ix_cost_estimates_"+c,"cost_estimates",[c])
 with op.batch_alter_table("structural_artifacts") as b:
  b.add_column(sa.Column("world_model_revision_id",sa.String(36)));b.add_column(sa.Column("design_alternative_id",sa.String(36)));b.add_column(sa.Column("input_world_model_hash",sa.String(64),nullable=False,server_default=s("")));b.add_column(sa.Column("input_design_hash",sa.String(64),nullable=False,server_default=s("")));b.add_column(sa.Column("input_geometry_hash",sa.String(64),nullable=False,server_default=s("")));b.add_column(sa.Column("engine_name",sa.String(80),nullable=False,server_default=s("legacy")));b.add_column(sa.Column("engine_version",sa.String(40),nullable=False,server_default=s("legacy")));b.add_column(sa.Column("config_version",sa.String(40),nullable=False,server_default=s("legacy")));b.add_column(sa.Column("concept_hash",sa.String(64)));b.add_column(sa.Column("assumptions_json",J,nullable=False,server_default=s("[]")));b.add_column(sa.Column("warnings_json",J,nullable=False,server_default=s("[]")));b.add_column(sa.Column("unknowns_json",J,nullable=False,server_default=s("[]")));b.add_column(sa.Column("provenance_json",J,nullable=False,server_default=s("{}")));b.add_column(sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False,server_default=NOW));b.create_foreign_key("fk_struct_world","world_model_revisions",["world_model_revision_id"],["id"]);b.create_foreign_key("fk_struct_alt","design_alternatives",["design_alternative_id"],["id"]);b.create_unique_constraint("uq_structural_hash_per_version",["project_version_id","concept_hash"])
 for c in ["world_model_revision_id","design_alternative_id","concept_hash","status"]:op.create_index("ix_structural_artifacts_"+c,"structural_artifacts",[c])
 with op.batch_alter_table("regulatory_evaluations") as b:
  b.add_column(sa.Column("world_model_revision_id",sa.String(36)));b.add_column(sa.Column("design_alternative_id",sa.String(36)));b.add_column(sa.Column("input_world_model_hash",sa.String(64),nullable=False,server_default=s("")));b.add_column(sa.Column("input_design_hash",sa.String(64),nullable=False,server_default=s("")));b.add_column(sa.Column("input_geometry_hash",sa.String(64),nullable=False,server_default=s("")));b.add_column(sa.Column("engine_name",sa.String(80),nullable=False,server_default=s("legacy")));b.add_column(sa.Column("engine_version",sa.String(40),nullable=False,server_default=s("legacy")));b.add_column(sa.Column("config_version",sa.String(40),nullable=False,server_default=s("legacy")));b.add_column(sa.Column("regulatory_hash",sa.String(64)));b.add_column(sa.Column("provenance_json",J,nullable=False,server_default=s("{}")));b.add_column(sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False,server_default=NOW));b.create_foreign_key("fk_reg_world","world_model_revisions",["world_model_revision_id"],["id"]);b.create_foreign_key("fk_reg_alt","design_alternatives",["design_alternative_id"],["id"]);b.create_unique_constraint("uq_regulatory_hash_per_version",["project_version_id","regulatory_hash"])
 for c in ["world_model_revision_id","design_alternative_id","ruleset_id","regulatory_hash","status"]:op.create_index("ix_regulatory_evaluations_"+c,"regulatory_evaluations",[c])
 with op.batch_alter_table("validation_runs") as b:
  b.add_column(sa.Column("world_model_revision_id",sa.String(36)));b.add_column(sa.Column("design_alternative_id",sa.String(36)));b.add_column(sa.Column("input_hashes_json",J,nullable=False,server_default=s("{}")));b.add_column(sa.Column("engine_name",sa.String(80),nullable=False,server_default=s("legacy")));b.add_column(sa.Column("engine_version",sa.String(40),nullable=False,server_default=s("legacy")));b.add_column(sa.Column("config_version",sa.String(40),nullable=False,server_default=s("legacy")));b.add_column(sa.Column("validation_hash",sa.String(64)));b.add_column(sa.Column("provenance_json",J,nullable=False,server_default=s("{}")));b.add_column(sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False,server_default=NOW));b.create_foreign_key("fk_validation_world","world_model_revisions",["world_model_revision_id"],["id"]);b.create_foreign_key("fk_validation_alt","design_alternatives",["design_alternative_id"],["id"]);b.create_unique_constraint("uq_validation_hash_per_version",["project_version_id","validation_hash"])
 for c in ["world_model_revision_id","design_alternative_id","validation_hash","status"]:op.create_index("ix_validation_runs_"+c,"validation_runs",[c])
 with op.batch_alter_table("rate_schedules") as b:
  b.add_column(sa.Column("jurisdiction",sa.String(120),nullable=False,server_default=s("unspecified")));b.add_column(sa.Column("currency",sa.String(3),nullable=False,server_default=s("SAR")));b.add_column(sa.Column("source_type",sa.String(32),nullable=False,server_default=s("USER_PROVIDED")));b.add_column(sa.Column("source_reference",sa.String(500),nullable=False,server_default=s("")));b.add_column(sa.Column("effective_date",sa.String(40),nullable=False,server_default=s("")));b.add_column(sa.Column("status",sa.String(24),nullable=False,server_default=s("ACTIVE")))
 op.create_index("ix_rate_schedules_status","rate_schedules",["status"])
 with op.batch_alter_table("regulatory_rulesets") as b:b.add_column(sa.Column("authority",sa.String(200),nullable=False,server_default=s("unconfigured")))
 with op.batch_alter_table("regulatory_rules") as b:
  b.add_column(sa.Column("parameter",sa.String(100),nullable=False,server_default=s("")));b.add_column(sa.Column("operator",sa.String(24),nullable=False,server_default=s("exists")));b.add_column(sa.Column("threshold_json",J));b.add_column(sa.Column("unit",sa.String(40)));b.add_column(sa.Column("source_reference",sa.String(500),nullable=False,server_default=s("")));b.add_column(sa.Column("effective_date",sa.String(40),nullable=False,server_default=s("")))
 with op.batch_alter_table("validation_checks") as b:b.add_column(sa.Column("severity",sa.String(24),nullable=False,server_default=s("INFO")));b.add_column(sa.Column("category",sa.String(60),nullable=False,server_default=s("GENERAL")));b.add_column(sa.Column("source_artifact_id",sa.String(36)))

def downgrade():
 with op.batch_alter_table("validation_checks") as b:
  for c in ["source_artifact_id","category","severity"]:b.drop_column(c)
 with op.batch_alter_table("regulatory_rules") as b:
  for c in ["effective_date","source_reference","unit","threshold_json","operator","parameter"]:b.drop_column(c)
 with op.batch_alter_table("regulatory_rulesets") as b:b.drop_column("authority")
 op.drop_index("ix_rate_schedules_status",table_name="rate_schedules")
 with op.batch_alter_table("rate_schedules") as b:
  for c in ["status","effective_date","source_reference","source_type","currency","jurisdiction"]:b.drop_column(c)
 def drop_expanded(table,prefix,indexes,constraints,fks,columns):
  for c in indexes:op.drop_index(f"ix_{prefix}_{c}",table_name=table)
  with op.batch_alter_table(table) as b:
   for x in constraints:b.drop_constraint(x,type_="unique")
   for x in fks:b.drop_constraint(x,type_="foreignkey")
   for c in columns:b.drop_column(c)
 drop_expanded("validation_runs","validation_runs",["world_model_revision_id","design_alternative_id","validation_hash","status"],["uq_validation_hash_per_version"],["fk_validation_world","fk_validation_alt"],["updated_at","provenance_json","validation_hash","config_version","engine_version","engine_name","input_hashes_json","design_alternative_id","world_model_revision_id"])
 drop_expanded("regulatory_evaluations","regulatory_evaluations",["world_model_revision_id","design_alternative_id","ruleset_id","regulatory_hash","status"],["uq_regulatory_hash_per_version"],["fk_reg_world","fk_reg_alt"],["updated_at","provenance_json","regulatory_hash","config_version","engine_version","engine_name","input_geometry_hash","input_design_hash","input_world_model_hash","design_alternative_id","world_model_revision_id"])
 drop_expanded("structural_artifacts","structural_artifacts",["world_model_revision_id","design_alternative_id","concept_hash","status"],["uq_structural_hash_per_version"],["fk_struct_world","fk_struct_alt"],["updated_at","provenance_json","unknowns_json","warnings_json","assumptions_json","concept_hash","config_version","engine_version","engine_name","input_geometry_hash","input_design_hash","input_world_model_hash","design_alternative_id","world_model_revision_id"])
 drop_expanded("cost_estimates","cost_estimates",["world_model_revision_id","design_alternative_id","geometry_artifact_id","cost_hash","status"],["uq_cost_hash_per_version"],["fk_cost_world","fk_cost_alt","fk_cost_geom"],["updated_at","provenance_json","uncertainty_json","unknowns_json","assumptions_json","status","high_estimate","low_estimate","total_cost","direct_cost","currency","cost_hash","config_version","engine_version","engine_name","input_rate_schedule_hash","input_quantity_hash","geometry_artifact_id","design_alternative_id","world_model_revision_id"])
 drop_expanded("quantity_artifacts","quantity_artifacts",["world_model_revision_id","design_alternative_id","quantity_hash","status"],["uq_quantity_hash_per_version"],["fk_quantity_world","fk_quantity_alt"],["updated_at","provenance_json","uncertainty_json","unknowns_json","assumptions_json","status","quantity_hash","config_version","engine_version","engine_name","input_geometry_hash","input_design_hash","input_world_model_hash","design_alternative_id","world_model_revision_id"])
 op.drop_table("regulatory_results");op.drop_table("rate_entries")
